### ISSUE TITLE
EXC_BREAKPOINT in OrdersViewController

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#2186] opened 2020-04-24 09:10 UTC
Sentry Issue: [WOOCOMMERCE-IOS-4D](https://sentry.io/organizations/a8c/issues/1626244074/?referrer=github_integration)

```
EXC_BREAKPOINT: Fatal error
  File "SyncCoordinator.swift", line 116, in SyncingCoordinator.synchronize
  File "Classes/Tools/SyncCoordinator.swift", line 103, in SyncingCoordinator.synchronizeFirstPage
  File "ReviewsViewController.swift", line 132, in ReviewsViewController.presentDetails
  File "MainTabBarController.swift", line 330, in MainTabBarController.presentNotificationDetails
  File "MainTabBarController.swift", line 166, in MainTabBarController.navigateTo
...
(14 additional frame(s) were not displayed)
```

**Comment by shiki** [comment] 2020-08-24 23:16
This looks like a duplicate of #2254 which has already been fixed.

**Closed by shiki** 2020-08-24 23:16 UTC
Labels: [Feat] Order List, [Type] Crash
