### ISSUE TITLE
Order Status is not localized

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-ios#1843] opened 2020-02-07 19:38 UTC
**Describe the bug**
To start with, I want to be clear that this _may_ not be a bug. Order status, IIRC, is fetched from the server, and I'd imagine that the default status set is localized server-side – perhaps we're not passing enough data to the endpoint to fetch them? Or, perhaps as in the case of the store currency, this is deliberately not localized but instead respects the value set in the store's options?

**To Reproduce**
Set the simulator to a different language. Search within orders.

**Screenshots**
| Arabic        | French           |
| ------------- |-------------|
| <img src="https://user-images.githubusercontent.com/1123407/74059912-1e4d4280-49a6-11ea-9370-b7bb84ad4ba9.png" width="250px" />      | <img src="https://user-images.githubusercontent.com/1123407/74060141-90258c00-49a6-11ea-8814-5bca258c6f3a.png" width="250px" />  |

**Expected behaviour**
I _think_ I'd expect these labels to be localized, assuming the server can provide that data.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Simulator (all types)
- iOS version: 13.3
- WooCommerce iOS version: `develop`

**WordPress Environment**
<details>
WP.com-hosted WooCommerce
</details>

**Comment by shiki** [comment] 2020-09-18 23:16
@jkmassel Thank you for reporting this. I agree that this is most probably not a bug. These values are not hardcoded in the app. They are taken from the API. We fetch the order statuses here:

https://github.com/woocommerce/woocommerce-ios/blob/4bfcb596ef5507b03e79e6c08a0e3c9b9786c9ec/WooCommerce/Classes/ViewRelated/Orders/OrdersMasterViewModel.swift#L46-L63

And then we display the fetched statuses here:

https://github.com/woocommerce/woocommerce-ios/blob/4bfcb596ef5507b03e79e6c08a0e3c9b9786c9ec/WooCommerce/Classes/ViewRelated/Search/Order/OrderSearchStarterViewModel.swift#L86-L96

The endpoint used for this is [`reports/orders/totals`](https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-customers-totals) which does not provide any language override options as far as I know. 

### Translation

Users [can change the language in WooCommerce](https://docs.woocommerce.com/document/woocommerce-localization/). And if they do, the API will return the correct translation. Here's a sample of me changing the translation of “Failed” on the web. The API correctly returns the translated value and the app will display it as-is:

![image](https://user-images.githubusercontent.com/198826/93652491-746d7400-f9d2-11ea-9ee9-fc4cc1cbb0f3.png)

<img src="https://user-images.githubusercontent.com/198826/93652558-a979c680-f9d2-11ea-9474-f57f392fc92a.png" width="240">

---

I will close this issue then. 🙂

**Closed by shiki** 2020-09-18 23:16 UTC
Labels: [Type] Bug
