### ISSUE TITLE
Shipping Labels - Legacy Flow: Continue in Shipping Carrier and Rates does nothing

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-ios#14300] opened 2024-11-04 11:47 UTC
When proceeding through the Shipping Labels flow, the Shipping Carrier and Rates step
 doesn't react: tapping the Continue button does nothing. See attached video:

https://github.com/user-attachments/assets/ef00ac21-22ea-4e3f-9963-ae774e2006c9

## Steps

1. Create an order on your web store.
2. In the app, go to Orders.
3. Tap on the create order.
4. Tap on Create Shipping Labels
5. Fulfill the steps until Shipping Carrier and Rates

**Comment by dangermattic** [comment] 2024-11-04 11:47
Thanks for reporting! 👍

**Comment by rachelmcr** [comment] 2024-11-05 09:22
This is caused by the same backend issue reported in https://github.com/woocommerce/woocommerce-shipping/issues/871. Because a package can't be correctly selected in the previous step, the carrier step can't be completed.

I tested again with a version of the WCShip extension that includes the fix for that issue, and this issue is resolved. Closing since this is a backend issue and will be fixed for everyone when the new version of the extension is released.

**Closed as completed by rachelmcr** 2024-11-05 09:22 UTC
Labels: type: bug, feature: shipping labels, priority: high
