### ISSUE TITLE
[Menu] A gap in `Menu` screen.

### ISSUE THREAD

**Issue by pachlava** [woocommerce/woocommerce-ios#7754] opened 2022-09-21 17:48 UTC
**Describe the bug**
When opening `More` screen while being at any other screen (except for `Settings`, `Payments` and `Reviews`), this gray area is present:

![photo_2022-09-21 20 34 05](https://user-images.githubusercontent.com/73365754/191574919-a554bc7b-8f65-476b-92f9-74f9f7ee2bc9.jpeg)

It goes away after opening `Settings` and returning.

**To Reproduce**
1. Log in
2. Open `Menu` screen

**Mobile Environment**
- Device: iPhone 13 Pro
- iOS version: 16.0
- WooCommerce iOS version: 10.4.0.0 from TestFlight

**Comment by pmusolino** [comment] 2023-03-06 10:44
I'm not able to reproduce this issue anymore. I'm closing this issue for the moment 👍

**Closed as completed by pmusolino** 2023-03-06 10:44 UTC
Labels: type: bug, category: design, feature: hub menu
