### ISSUE TITLE
Numerous "Mobile App Woocommerce Thank You" pages were generated after resolving critical error

### ISSUE THREAD

**Issue by nazilya06** [woocommerce/woocommerce-ios#12286] opened 2024-03-15 14:18 UTC
**Describe the bug**
After a critical error on the site caused by the APPExperts plugin was fixed, I found that 658 pages titled "Mobile App Woocommerce Thank You" were generated. These pages seem to originate from the WooCommerce for iOS app, connected via OAuth2 to the site owner's account. 
We suspect that the WooCommerce iOS app scheduled a page that couldn't be published due to a critical error on the site and kept scheduling new pages. When the error was fixed, all pages were published at once.

**To Reproduce**
1. Go to Pages.
2. Find numerous pages titled "Mobile App Woocommerce Thank You."

<img width="2056" alt="Screenshot 2024-03-15 at 5 32 56 PM" src="https://github.com/woocommerce/woocommerce-ios/assets/118342580/56c6a452-5aa6-454f-bf5d-19b14b6fcb26">

**Expected behavior**
After resolving the critical error, the site should not automatically generate pages titled "Mobile App Woocommerce Thank You" without explicit user action.

Ticket: 7880228-zd-a8c

**Comment by dangermattic** [comment] 2024-03-15 14:30
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by rachelmcr** [comment] 2024-03-18 13:52
Thanks for the report @nazilya06! I'm curious about this part of the report:

> These pages seem to originate from the WooCommerce for iOS app

Could you share more about why you think these are coming from the app? As far as I know, the app doesn't have any support for publishing regular pages like these, and there's nothing to publish a page titled "Mobile App Woocommerce Thank You", so I can't think of how this would be caused by the app. If the app was a factor in the pages being published, though, we could certainly look into it; we'd just need more information about how to reproduce the issue to understand how the app is involved.

**Comment by rachelmcr** [comment] 2024-03-28 13:54
I'm going to close this issue because I don't see any way that the app generated these pages directly, and without more information we can't investigate further. If you get more details about how the app was involved, though, please feel free to reopen the issue and we can take another look!

**Closed as completed by rachelmcr** 2024-03-28 13:54 UTC
Labels: type: bug

**Comment by nazilya06** [comment] 2024-04-01 08:25
> I'm going to close this issue because I don't see any way that the app generated these pages directly, and without more information we can't investigate further. If you get more details about how the app was involved, though, please feel free to reopen the issue and we can take another look!

I am sorry for the late response. I was AFK. 
Unfortunately, I couldn't find any other indication besides page titles. Thank you for taking a look!
