### ISSUE TITLE
Order Creation: Improve Add a different shipping address toggle

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#6579] opened 2022-04-06 22:13 UTC
Reported by @jaclync in CFT

> If I disable “Add a different shipping address” toggle then tap “Done” to leave the screen, the toggle is still enabled after coming back to this screen

**Comment by jaclync** [comment] 2022-04-21 05:30
@selanthiraiyan and I cannot reproduce on the latest `trunk` anymore, closing this!

**Closed as completed by jaclync** 2022-04-21 05:30 UTC
Labels: type: enhancement, good first issue, feature: order creation
