### ISSUE TITLE
[Mobile Payments] [M2] First connection of M2 is rough with a dueling Pairing Request and "We couldn't connect" modal 

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5326] opened 2021-11-02 17:54 UTC
When connecting to an M2 reader for the first time, a "We couldn't connect your reader" modal is displayed with a "Bluetooth Pairing Request" superimposed on it:

![IMG_0227](https://user-images.githubusercontent.com/1595739/139919253-1fdcf763-aede-4a21-b4c3-c53c9394f5e7.PNG)

If you tap the Pair button you are NOT prompted for a PIN (I was expecting to be prompted) and before I could tap on the "Try Again" in the modal, the connection completed:

![IMG_0228](https://user-images.githubusercontent.com/1595739/139919362-b6c7114b-de53-4a4b-84c3-bbe60afd0455.PNG)

I mean, I was connected to the reader at the end of it all and was able to accept payments, but the experience is rough.

**Comment by ctarda** [comment] 2021-11-17 20:43
I am not sure there is much we can do here. The SDK seems to time out pretty fast when waiting for the user to insert the pin on first connection. 

The alert titled "Bluetooth pairing request" is presented by the system, by a direct request from the Terminal SDK. There is no delegate method or notification that I can find emitted by the SDK that we could hook into. 

The alert we present is doing what is expected from it. 

What is a bit concerning is that it is actually possible to connect without actually entering the pin (although I was not able to reproduce this). 

Anyway, I've let the SDK timeout waiting for the connection pin several times, tapped retry in our alert, navigated out of the connection flow and back into it several times, and I could not beak this.

@allendav  do you want to share this with Stripe, see if they have any suggestion?

**Comment by allendav** [comment] 2021-11-17 21:03
Yes lets. I'll record a video and share it with them asap

**Comment by ctarda** [comment] 2021-11-18 12:20
Update. Apparently, the PIN is only requested in beta readers: pdi1mn-2A#comment-72

**Comment by ctarda** [comment] 2021-11-24 11:13
Let's close this one for now.

**Closed as completed by ctarda** 2021-11-24 11:13 UTC
Labels: type: bug, feature: mobile payments
