### ISSUE TITLE
Photo of product missing on Products screen

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#5645] opened 2021-12-09 04:30 UTC
**Describe the bug**
Uploaded photos not displayed on Products screen but is displayed on web browser

**To Reproduce**
1. Go to Products screen and tap to add a new photo for the product
2. Add photo by taking new photo
2. Once upload is completed, see that photo is uploaded on screen
3. Exit and return to product screen
4. See that product photo is now missing (show the default "no image" image instead)
5. Go to Products listing page - see that thumbnail of product photo is also missing

**Screenshots**

https://user-images.githubusercontent.com/17252150/145334117-afb495c9-1cec-4baa-aba7-d8f1368be4eb.MP4

The same store on Web:
![image](https://user-images.githubusercontent.com/17252150/145334536-9551980a-c2bd-4cba-8aa2-11874b738232.png)

**Expected behavior**
Newly uploaded photo should be displayed 

**Isolating the problem (mark completed items with an [x]):**
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 Mini
- iOS version: 15.0
- WooCommerce iOS version: 18.1

**Comment by shiki** [comment] 2021-12-22 20:05
I can't seem to reproduce this. 

How about you, @jaclync or @pmusolino?

**Comment by jaclync** [comment] 2021-12-23 07:51
I tested on 2 sites and couldn't reproduce this issue either 🤔

**Comment by pmusolino** [comment] 2021-12-23 16:17
I am wondering if the images have strange names, and therefore the URL is not encoded correctly. An issue something similar to this https://github.com/woocommerce/woocommerce-ios/issues/2789
Maybe something changed under the hood in WooCommerce? 🤔 
By the way, I'm not able to reproduce it.

**Comment by shiki** [comment] 2022-10-06 22:44
Gonna close this. We'll reopen if it happens again.

**Closed as not planned by shiki** 2022-10-06 22:44 UTC
Labels: type: bug, feature: product details
