### ISSUE TITLE
Notification Badge: it doesn't disappear when you select Orders tab

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1388] opened 2019-10-22 11:33 UTC
#2438723-zen

It appears that the red badge count on the app icon is tied only to the Reviews screen, and not to the Orders screen.

The only way to get rid of the notification badge is to visit the reviews tab (also if reviews are disabled on the website).

Seems that the notification badge needs to be tied also to the Orders screen, and not only to Reviews.

Looking at the code
```
ServiceLocator.pushNotesManager.resetBadgeCount()
```
this method is called only inside `ReviewsViewController`, `NotificationsViewController` and `DefaultStoresManager`.

**Steps to reproduce the behavior:**
1. Get some push notifications about a new order.
2. Open the app.
3. Tap on Orders tab
4. The red badge on the app is still there.
5. Tap the Reviews tab.
6. The red badge disappear.

**Comment by rachelmcr** [comment] 2020-05-15 10:38
This came up in feedback from a beta tester (4.2 TestFlight beta):

> WC gets a notification badge whenever an order comes in. However, that badge does not clear when I open the app, or even after I have processed all orders. It only clears when I visit the Reviews part of the app (which is always empty).

I really think this and https://github.com/woocommerce/woocommerce-ios/issues/1735 are significant broken windows for users getting and processing new orders in the app. How much work would it be to resolve this?

**Comment by rachelmcr** [comment] 2020-05-15 10:47
The same beta tester also observed that even after the notification badge disappears, the badge count isn't reset. That means that when another new order comes in, the badge count increases by 1 from its previous count.

I reproduced it like this:

1. Get a push notification about a new order. Notice the red badge on the app and make a note of what the badge count is.
2. Open the app.
3. Tap on Orders tab.
4. The red badge on the app is still there.
5. Tap the Reviews tab.
6. The red badge disappears.
7. Get another push notifications about a new order. Notice the count on the red badge is increased by one from before, instead of being reset and showing "1" for the new notification.

**Comment by jaclync** [comment] 2020-05-18 05:38
thanks for raising this @rachelmcr! yes this issue is directly related to https://github.com/woocommerce/woocommerce-ios/issues/1735 where we currently can't differentiate push notifications from the two sources (new order, new review) and the reviews tab is handling the badge appearance/reset.

it's a long-standing broken window reported by many users, internally and externally. I'm taking it this sprint!

**Comment by jaclync** [comment] 2020-05-18 05:44
(related discussion p91TBi-2pK-p2)

**Comment by reginabally** [comment] 2021-12-15 03:24
I'm re-opening this issue because we received three reports so far on these tickets:

* 4612640-zd-woothemes
* 4567027-zd-woothemes
* 4558912-zd-woothemes

In two of the tickets, force-closing the app, logging out and logging back in didn't help. I've asked one of the users to check the Reviews tab to see if the badge goes away and will report back with the update.

**Comment by mdrockwell** [comment] 2021-12-16 16:51
4615938-zd-woothemes replied and said that checking the Reviews tab didn't help.

**Comment by mdrockwell** [comment] 2021-12-20 19:48
Another: 4625720-zd-woothemes

**Comment by reginabally** [comment] 2021-12-21 02:13
Another report here: 4620954-zd-woothemes

> All orders are gone in the woo app, there is still 1 in the picture

**Comment by reginabally** [comment] 2021-12-21 02:44
Another report: 4626990-zd-woothemes

> The Woo app shows there are new orders (icon with a number over it) but there are no new orders

**Comment by jaclync** [comment] 2021-12-22 02:12
Update: a hotfix release 8.1.1 is scheduled to fix this! (p1640101931099100-slack-C5ALGJYEP)

Let's close this issue after the hotfix release 8.1.1 is out and we don't get reports

**Comment by anitaa1990** [comment] 2022-03-08 08:55
Closing since this issue was fixed in #5715

**Closed by anitaa1990** 2022-03-08 08:55 UTC
Labels: type: bug, feature: order list, good first issue
