### ISSUE TITLE
[Order Details] Make Products and Refunded Products sections consistent across platforms

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#6902] opened 2022-05-19 09:19 UTC
> ![Android iOS comparison](https://user-images.githubusercontent.com/2472348/169253958-fdf3703f-3445-4c7e-ba14-14fe928c050c.png)
> 
> Android and iOS present refunded products differently. Both display a list of products in a section at the top. This section includes some action buttons – Mark Order Complete and, if available, Create Shipping Label. Android no longer shows these products in this list if any products are refunded and hides the whole section if all products are refunded – including the Mark Order Complete button. iOS displays all products in the Products section, even if some or all have been refunded.
> 
> Refunded products can be found on a separate screen on both platforms, accessed via a new button in a separate section. This section appears below the Products section. On iOS, if a shipping label has been created, the Refunded Products section appears below the Shipping Label.
> 
> – Context: p91TBi-8P0-p2#refunded-products-the-mark-as-complete-button

- [X] iOS should remove products from the `Products` section when they are refunded. Currently, products are shown in both `Products` and `Refunded Products` sections, when they are refunded
- [X] The `Products` section should be hidden when it's empty
- [X] The `Refunded Products` section should be hidden when it's empty
- [ ] ~The `Refunded Products` section should be moved to above the `Shipping Label` section~ Moved to #7073 for clarity

**Comment by toupper** [comment] 2022-05-24 09:14
Hi @joe-keenan I was trying to reproduce the cases described above, and I couldn't reproduce some of them, it seems like the behavior is already the one intended here, with the iOS app version of 9.2.0.1 from Testflight:

>  iOS should remove products from the Products section when they are refunded. Currently, products are shown in both Products and Refunded Products sections, when they are refunded

This is not my experience:

<img src="https://user-images.githubusercontent.com/1864060/169995374-8c7f271d-4f9f-4e38-946f-690be9f3e22e.png" width="375"> | <img src="https://user-images.githubusercontent.com/1864060/169995392-c85f2080-8a97-4eab-ac47-63133e54b0cb.png" width="375">

As you can see, the refunded product does not appear in the products list.

>  The Products section should be hidden when it's empty
>  The Refunded Products section should be hidden when it's empty

<img src="https://user-images.githubusercontent.com/1864060/169995894-e61ca5f1-85c4-46f8-8453-48400fada911.png" width="375">

This order has neither products nor refunded products, and both sections are hidden.

Is there perhaps a series of steps to reproduce that state which I am missing? Thanks a lot

**Comment by joe-keenan** [comment] 2022-05-25 01:20
Hey @toupper, I thought I must be crazy when I saw your screenshots! But I just tried to replicate it myself and it turned out just like I described. Here’s a video:

https://user-images.githubusercontent.com/95003933/170157984-03502594-333b-44db-a0cc-22ad649d5573.mp4

**Comment by toupper** [comment] 2022-05-25 09:04
@joe-keenan Thanks for your answer, now I thought as well that I am crazy, but when replicating your steps I only see the not refunded products there 😄 

https://user-images.githubusercontent.com/1864060/170224558-d372155e-baa0-4a44-b0dd-6d86aad4fb33.mp4

So it seems more like a bug caused by some conditions that we don't know yet. Could you tell me what app version are you using? Furthermore, perhaps you can invite me to your test store (it doesn't have to be admin) so I can test these conditions.

Thanks a lot!

**Comment by joe-keenan** [comment] 2022-05-25 09:21
Hey César, it all sounds pretty weird! You’re right, though. It’s more like a bug. 

Can you show me what happens if you refund both products? I’d like to see if both the Shipping Label and Mark Order Complete buttons get hidden with the Products section.

The app versions are 1648139008 (ebea784-trunk) and 9.2 (9.2.0.0). Happens in both. I’ve invited you to the store to check it out, anyway. Good luck with it!

**Comment by toupper** [comment] 2022-05-25 09:32
Thanks @joe-keenan for your quick answer and the info provided :) 

> Can you show me what happens if you refund both products? I’d like to see if both the Shipping Label and Mark Order Complete buttons get hidden with the Products section.

Here you go:

https://user-images.githubusercontent.com/1864060/170230491-c0032697-1f94-40f2-902a-ff3e571d74ec.mp4

Yes, they get hidden after I refund the second product.

I will check it now in your store 😃

**Comment by toupper** [comment] 2022-05-25 09:35
btw @joe-keenan  could you please change my role to shop manager? I forgot that the app only support shop manager or admin roles 😅 Sorry for that!

<img src="https://user-images.githubusercontent.com/1864060/170231345-b7e26633-5728-42c1-ae60-be2f0bad0b21.png" width="375">

**Comment by joe-keenan** [comment] 2022-05-30 03:06
Sorry about that @toupper! I’ll have to remember that in future!

I’ve changed it, and thanks for the video. It looks like my recommendations about keeping the `Mark Order Complete` button visible will apply to both platforms now.

**Comment by joshheald** [comment] 2022-06-28 09:56
@toupper Should this be closed by one of your other PRs now? I thought the work you did on variations resolved it... but maybe it was preparatory work for this?

**Comment by toupper** [comment] 2022-06-28 10:00
@joshheald That PR fixed the first point:

But I have to double check that the last two points are also solved before closing this issue:

iOS should remove products from the Products section when they are refunded. Currently, products are shown in both Products and Refunded Products sections, when they are refunded

 The Products section should be hidden when it's empty
 The Refunded Products section should be hidden when it's empty

**Comment by joshheald** [comment] 2022-06-28 10:31
@toupper 👍 Ok, thanks for the clarification. If they're not solved, we can move them to a new (on hold) issue and close this one, so that it's clear what's still to do if we need to park this project.

**Comment by toupper** [comment] 2022-06-28 12:53
@joshheald Now I checked and it works fine also for the other two points, I proceed to close it now.

**Closed as completed by toupper** 2022-06-28 12:53 UTC
Labels: type: enhancement, feature: order details, category: parity
