### ISSUE TITLE
With App Language Set to German, There Is a Phantom ”Bestellungen” (Orders) Label

### ISSUE THREAD

**Issue by igotdes** [woocommerce/woocommerce-ios#7760] opened 2022-09-23 06:29 UTC
**Describe the bug**

With the app language set to German, there is a phantom ”Bestellungen” (Orders) label at the lower-left corner of the screen.

**To Reproduce**
1. Set your phone's primary language to Deutsch
2. Open the WooCommerce mobile app
3. Click the ”Bestellungen” (Orders) tab
4. A phantom ”Bestellungen” (Orders) label will appear at the lower-left corner of the screen

**Screenshots**

![IMG_0014](https://user-images.githubusercontent.com/74066241/191902910-9614c9c3-cfb9-48e0-8083-9a153ed33995.png)

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone SE 2022
- iOS version: 16.0
- WooCommerce iOS version: 10.4.0.0

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): [[...]]
Site address (URL): [[...]]
WC Version: 6.9.3
REST API Version: ✔ 6.9.3
WC Blocks Version: ✔ 8.3.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.30
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.83.1
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.3
WC Database Prefix: wp_
Total Database Size: 3.95MB
Database Data Size: 2.39MB
Database Index Size: 1.56MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.06MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.20MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.20MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

amp_validated_url: 1
attachment: 31
customize_changeset: 5
jetpack_migration: 2
jp_img_sitemap: 4
jp_sitemap: 4
jp_sitemap_master: 4
nav_menu_item: 6
page: 7
post: 4
product: 18
product_variation: 7
revision: 6
shop_coupon: 1
shop_order: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Akismet Anti-Spam: by Automattic – 5.0
AMP: by AMP Project Contributors – 2.3.0
CoBlocks: by GoDaddy – 2.24.4
Crowdsignal Forms: by Automattic – 1.6.6
WordPress.com Editing Toolkit: by Automattic – 3.43445
Gutenberg: by Gutenberg Team – 14.1.1
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 11.4-a.7
Layout Grid: by Automattic – 1.8.2
Page Optimize: by Automattic – 0.5.2
WooCommerce: by Automattic – 6.9.3

### Inactive Plugins (1) ###

Classic Editor: by WordPress Contributors – 1.6.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #30 - /
Cart: #31 - /cart/
Checkout: #32 - /checkout/
My account: #33 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-09-23 16:30:12 +08:00
Options: ✔
Notes: 92
Onboarding: skipped

### Action Scheduler ###

Complete: 8
Oldest: 2022-09-16 10:38:28 +0800
Newest: 2022-09-23 14:28:07 +0800

Pending: 1
Oldest: 2022-09-23 16:24:49 +0800
Newest: 2022-09-23 16:24:49 +0800


### Status report information ###

Generated at: 2022-09-23 14:28:37 +08:00
`
```
</details>

**Comment by rachelmcr** [comment] 2024-08-19 13:19
I can no longer reproduce this issue (tested with German on iPhone 12 mini, iOS 18 beta, WooCommerce iOS 20.0 beta). This was likely fixed in iOS/SwiftUI since the initial report.

Please feel free to reopen the issue if it's still a problem!

**Closed as completed by rachelmcr** 2024-08-19 13:19 UTC
Labels: type: bug, feature: order list, priority: low
