### ISSUE TITLE
No preview product option for variable products through the order details screen

### ISSUE THREAD

**Issue by reginabally** [woocommerce/woocommerce-ios#4609] opened 2021-07-14 05:24 UTC
**Describe the bug**

Originally reported on WCAndroid: https://github.com/woocommerce/woocommerce-android/issues/4429

The "View Product in Store" option went missing when accessing the product through the order details screen.

**To Reproduce**
1. Go to Orders, select an order that has a variable product.
2. Tap the variable product to see the product details.
3. See that the three dots are missing on the top right corner of the screen and there's no way to select the "View Product in Store" option.

**Screen recording**

https://user-images.githubusercontent.com/40906847/125567288-98fbfabe-a9b4-43ed-ab4a-b4a4e6454261.MP4

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone SE
- iOS version: 14.6
- WooCommerce iOS version: 7.0.0.2

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://woo20210709.mystagingwebsite.com
Site address (URL): https://woo20210709.mystagingwebsite.com
WC Version: 5.4.1
REST API Version: ✔ 5.4.1
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.21
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.77.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.20-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.1
WC Database Prefix: wp_
Total Database Size: 4.79MB
Database Data Size: 3.32MB
Database Index Size: 1.47MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.25MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
customize_changeset: 1
page: 6
post: 1
product: 24
product_variation: 9
shop_order: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Jetpack: by Automattic – 9.9
WooCommerce: by Automattic – 5.4.1 (update to version 5.5.0 is available)

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.10
WooCommerce Shipping & Tax: by WooCommerce – 1.25.15 (update to version 1.25.17 is available)

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 10
Oldest: 2021-07-09 06:32:23 +0000
Newest: 2021-07-14 05:07:22 +0000

Pending: 1
Oldest: 2021-07-14 05:15:48 +0000
Newest: 2021-07-14 05:15:48 +0000


### Status report information ###

Generated at: 2021-07-14 05:14:58 +00:00
````
</details>

**Comment by iamgabrielma** [comment] 2021-08-15 14:31
This seems to be kind of expected, the option does not show because has been made to fail on purpose, here: 

```
        /// The "View product in store" action will be shown only if the product is published.
        if viewModel.canViewProductInStore() {
            actionSheet.addDefaultActionWithTitle(ActionSheetStrings.viewProduct) { [weak self] _ in
                ServiceLocator.analytics.track(.productDetailViewProductButtonTapped)
                self?.displayWebViewForProductInStore()
            }
        }
```

Then specifically the `ProductVariationFormViewModel` contains this bit:

```
    func canViewProductInStore() -> Bool {
        false
    }
```
What I don't know is this is a "won't fix" for any particular reason, or is just because has not been implemented just yet. My guess is that has not been implemented yet, and we could just show the main product if the button is tapped ( as variable products don't have their own page ) . 

cc: @Ecarrion for context, as worked on this implementation.

**Comment by Ecarrion** [comment] 2022-01-25 14:44
Hi @iamgabrielma sorry for missing this notification 🙈 I don't think I implemented that part, but after looking at the code it seems that this was just overlooked. I think it's safe to work on this!

**Comment by Ecarrion** [comment] 2022-01-25 14:45
Assigning this to a trial candidate!

**Comment by chrisKns** [comment] 2022-02-06 20:40
@Ecarrion  I think as we enabled `canViewProductInStore()` in [this PR](https://github.com/woocommerce/woocommerce-ios/pull/6091) we can also enabled `canShareProduct()` like this for a product variation:

    func canShareProduct() -> Bool {
        formType != .add
    }

**Comment by Ecarrion** [comment] 2022-02-07 13:41
> @Ecarrion I think as we enabled `canViewProductInStore()` in [this PR](https://github.com/woocommerce/woocommerce-ios/pull/6091) we can also enabled `canShareProduct()` like this for a product variation:
> 
> ```
> func canShareProduct() -> Bool {
>     formType != .add
> }
> ```

I think we can, yeah!

**Closed as completed** 2022-02-07 19:34 UTC
Labels: type: bug, feature: order details, good first issue
