### ISSUE TITLE
Order Creation: Product List is unresponsive when keyboard is visible

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#14026] opened 2024-09-24 03:25 UTC
# Description

- Navigate to the orders tab
- Tap + to create an order
- Tap "Add Products" CTA
- Search for a product (do not tap "accept" button on the keyboard)
- See that the list is not responsive until the "Accept" button is tapped

https://github.com/user-attachments/assets/e5db72bb-9681-4503-8f56-d5ef91b15b14

**Comment by dangermattic** [comment] 2024-09-24 03:25
Thanks for reporting! 👍

**Comment by rachelmcr** [comment] 2024-09-24 07:39
Odd! For what it's worth, I couldn't reproduce this on my end (iPhone 12 mini, iOS 18.0, WCiOS 20.5 TestFlight beta). I tried the same search you did and others, and the list remained responsive even while the keyboard was on screen.

**Comment by Ecarrion** [comment] 2024-09-24 16:16
@rachelmcr it seems that it doesn't happen all the time, but it still happens on 20.5. Sadly the screen recording does not capture my touches

https://github.com/user-attachments/assets/99ea80be-87bf-4430-a1d6-f0332ff1f5f9

**Comment by bozidarsevo** [comment] 2024-12-09 11:19
Tested it now with 21.2 (21.1.0.1) and was not able to reproduce it.
Should we close it?

**Comment by rachelmcr** [comment] 2024-12-09 11:34
I still can't reproduce it, either. There may still be certain conditions to reproduce it, but for now let's close it. We can reopen if we get another report about the issue with more details.

**Closed as completed by rachelmcr** 2024-12-09 11:34 UTC
Labels: type: bug, feature: order creation
