### ISSUE TITLE
Applied coupon showing just in bottom details sheet

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#13861] opened 2024-09-05 11:29 UTC
I applied the coupon on an order and it shows in the details bottom sheet but I would expect it to show also where the “Add Coupon” is.

<img src="https://github.com/user-attachments/assets/73088cd7-c08e-4e4f-9990-5ed913670bc5" width="250px" />

**Comment by dangermattic** [comment] 2024-09-05 11:29
Thanks for reporting! 👍

**Comment by toupper** [comment] 2024-09-06 10:50
Closing the issue as this was an intended design decision to keep the order buttons area as clean as possible

**Comment by toupper** [comment] 2024-09-10 09:37
Confirmed from @joe-keenan that this should be indeed improved. We can take the Shipping section as reference and review with Joe if necessary. pe5pgL-5G4-p2#comment-4489

**Comment by iamgabrielma** [comment] 2024-10-22 01:20
Completed via https://github.com/woocommerce/woocommerce-ios/pull/14107. Closing!

**Closed as completed by iamgabrielma** 2024-10-22 01:20 UTC
Labels: type: enhancement, feature: order creation, priority: medium
