### ISSUE TITLE
Broken layout constraints in Issue Refunds screen

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3080] opened 2020-10-29 11:16 UTC
Trying to open the `Issue Refunds` screen from an iPhone 11 Pro simulator running iOS 14.1, I encountered these warnings about broken constraints:

```
<NSLayoutConstraint:0x60000259e2b0 UIButtonLabel:0x7ffc62c4b240.centerX == UIButton:0x7ffc62c173a0'Refund'.centerX   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-10-29 12:07:38.586939+0100 WooCommerce[39378:3751299] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x60000259dcc0 UILayoutGuide:0x600003f01180'UIViewSafeAreaLayoutGuide'.leading == UIButton:0x7ffc62c173a0'Refund'.leading - 16   (active)>",
    "<NSLayoutConstraint:0x60000259dd10 UILayoutGuide:0x600003f01180'UIViewSafeAreaLayoutGuide'.trailing == UIButton:0x7ffc62c173a0'Refund'.trailing + 16   (active)>",
    "<NSLayoutConstraint:0x60000259e440 'fittingSizeHTarget' WooCommerce.ButtonTableFooterView:0x7ffc62c47970.width == 0   (active)>",
    "<NSLayoutConstraint:0x60000259db80 'UIViewSafeAreaLayoutGuide-left' H:|-(0)-[UILayoutGuide:0x600003f01180'UIViewSafeAreaLayoutGuide'](LTR)   (active, names: '|':WooCommerce.ButtonTableFooterView:0x7ffc62c47970 )>",
    "<NSLayoutConstraint:0x60000259dc70 'UIViewSafeAreaLayoutGuide-right' H:[UILayoutGuide:0x600003f01180'UIViewSafeAreaLayoutGuide']-(0)-|(LTR)   (active, names: '|':WooCommerce.ButtonTableFooterView:0x7ffc62c47970 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000259dd10 UILayoutGuide:0x600003f01180'UIViewSafeAreaLayoutGuide'.trailing == UIButton:0x7ffc62c173a0'Refund'.trailing + 16   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

**Comment by Ecarrion** [comment] 2020-11-30 16:25
I played around a bit with this but have no clue about what is happening here :-/ 
The layout seems correct tho.

@shiki So you think you can take a look at it since you created `ButtonTableFooterView` maybe you'll have an idea!

PS: the warning happens after tapping next on the issue refund screen.

**Comment by shiki** [comment] 2020-12-01 00:34
I can take a look but I'm not sure **when**. 😅 I'm looking at prioritizing crashes at the moment.

**Comment by selanthiraiyan** [comment] 2021-10-12 14:26
Hello @shiki 👋  

I have identified that this is an issue with the `UIAlertController`. 

I was able to reproduce the constraints related warning in iPhone 11 Pro simulator running iOS 14.1. Please refer to the screen recording found below.

![WithActionSheet - iOS 14 1](https://user-images.githubusercontent.com/524475/136972259-03d442ee-f4b7-4094-bcc1-9ed4ec200b32.gif)


Then, I commented out the code for presenting the `UIAlertController` from `IssueRefundCoordinatingController` and tested in iPhone 11 Pro simulator running iOS 14.1 again. And, I couldn't see this warning this time. This way I made sure that the warning is caused by the `UIAlertController`. 

![WithoutActionSheet - iOS 14 1](https://user-images.githubusercontent.com/524475/136972681-a57f794f-3455-4816-afbb-2fbfc619cfa2.gif)

Also, I tested with iPhone 11 Pro simulator running iOS 14.5 and I couldn't reproduce this issue. Looks like, this issue with the `UIAlertController` has been fixed by Apple in iOS 14.5. 

![WithActionSheet - iOS 14 5](https://user-images.githubusercontent.com/524475/136973092-de8b1576-d824-4833-8d80-353aa10c4486.gif)

I think **this issue can be closed**. Kindly let me know your thoughts. Thank you.

Reference:
https://stackoverflow.com/questions/55653187/swift-default-alertviewcontroller-breaking-constraints
https://stackoverflow.com/questions/55372093/uialertcontrollers-actionsheet-gives-constraint-error-on-ios-12-2-12-3

P.S
I apologize for the low-quality gifs. I couldn't upload the `mov` format videos as they were larger than 10 MB. Kindly let me know if there is a better alternative.

**Comment by Ecarrion** [comment] 2021-10-12 16:14
Thanks for the thorough investigation @selanthiraiyan! 🙇 
I'm going to close this for now!

@shiki can reopen if he feels like taking a look! 😃

**Closed as completed by Ecarrion** 2021-10-12 16:14 UTC
Labels: type: bug, priority: low

**Comment by shiki** [comment] 2021-10-12 17:42
Thank you very much for the help, @selanthiraiyan! 🙇
