### ISSUE TITLE
No price banner not showing in the product details

### ISSUE THREAD

**Issue by rossanafmenezes** [woocommerce/woocommerce-ios#5263] opened 2021-10-21 20:33 UTC
While working on the Android version of [this](https://github.com/woocommerce/woocommerce-ios/issues/4451) I came across an unexpected behaviour related to the banner. The "no price" warning banner only shows if you tap the variation tab first. 

## Steps to reproduce

- Go to the products screen
- Open a variable product that has no price set for one of the variations. 

## Expected behaviour

The Warning Banner saying the variation without a price won't show in their store should be displayed in the product details screen

## What happens instead?

When you open the product there's is no banner:

![photo_2021-10-21 14 57 15](https://user-images.githubusercontent.com/30724184/138349533-efca2e17-0deb-4c60-a20f-95d94984a3f1.jpeg)

However, if you click on the Variations tab and then go back to the product details screen the banner is displayed:

![photo_2021-10-21 14 57 19](https://user-images.githubusercontent.com/30724184/138349588-e5439935-25e8-41a8-93d7-7dc56758df82.jpeg)

**Comment by selanthiraiyan** [comment] 2021-11-04 04:05
@rossanafmenezes 
Thank you for reporting this issue. 🙌 

I tried taking a look into this, but, I couldn't reproduce it by following the provided steps. 
I did a clean install and I had a variable product that had no price set.
![NoPriceWarningDisplayedOnCleanInstall](https://user-images.githubusercontent.com/524475/140255289-ab595d9f-b509-4079-acd3-68ff19f6cd9f.gif)
As seen in the above gif, I can see the no price set warning as soon as I open the product detail screen.
Kindly let me know if I am not following the right steps to reproduce this issue. 

Also, could this be an edge case scenario where the variations were altered simultaneously on the website? i.e. Apparently, we aren't reloading the variations in the product details screen (`ProductFormViewController`). 

The reload/change of the variations happens in the following places,
1. Products home screen (on reloading the screen) - `ProductsViewController`
2. In the Variation details screen - `ProductVariationsViewController`. (The Product detail screen  is notified using a `onProductUpdate` closure in this case.)

Thank you!

**Comment by rossanafmenezes** [comment] 2021-11-04 11:01
@selanthiraiyan  Hai! 👋 

Interesting. 🤔  I can reproduce it consistently on my iPad and I think @Ecarrion was able to reproduce it as well

https://user-images.githubusercontent.com/30724184/140302559-aa1949dd-317b-4f2d-b384-fe6d27728110.mp4

I noticed I was on version 7.7, just updated but still get the same behaviour. Now I'm intrigued 😅

**Comment by selanthiraiyan** [comment] 2021-11-04 12:48
Hello and thanks for checking @rossanafmenezes ! 👋 

This is really interesting. I am wondering whether this could be related to the store configuration and the number of products in it. I had only a few products (2 to be exact) set up in my store. 
Would it be possible for you to test this in a different store with a fewer number of products?

FYI - I am an outside contributor and I use https://tastewp.com/ to setup store.

**Comment by hafizrahman** [comment] 2024-01-26 06:49
Tried this today and do not see the issue. The banner is shown immediately:

https://github.com/woocommerce/woocommerce-ios/assets/266376/a7f705df-87f6-4bd5-af27-ea27e35913ca

There doesn't seem to be outside reports about this anymore. I'm going to close this to tidy up the repo but feel free to reopen when there's new reports.

**Closed as completed by hafizrahman** 2024-01-26 06:49 UTC
Labels: type: bug, feature: variation details
