### ISSUE TITLE
Products: Discard changes prompt can appear even when changes were already reverted

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1959] opened 2020-03-13 12:20 UTC
**Describe the bug**

I only expect the discard changes prompt to appear when there are still changes to product settings. If I make a change and manually revert it, I don't expect to see the discard changes prompt.

However, changes to certain fields (price, stock quantity) trigger the discard changes prompt even if I revert the change I made.

**To Reproduce**
1. Go to the Products tab.
2. Select a product.
3. Select "Price."
4. Make a change to the product price.
5. Change the product price back to its original value.
6. Tap the back button, and notice that the discard changes prompt appears even though the price settings are the same as before. Discard your changes.
7. Select "Inventory."
8. Enable the "Manage stock" toggle.
9. Change the quantity.
10. Revert your change (i.e. delete the quantity and disable the "manage stock" toggle).
11. Tap the back button, and notice that the discard changes prompt appears even though the price settings are the same as before. Discard your changes.

**Screenshots**

Screencast: https://cloudup.com/cfg737z7-W9

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3.1
- WooCommerce iOS version: 3.8.0.0 TestFlight beta

**Comment by jaclync** [comment] 2020-03-16 09:19
@rachelmcr thanks for the screencast, I was able to reproduce both cases under the price and inventory settings!

### Price settings

For price settings, it was when the tax class (slug) is "standard", which is represented by an empty string after saving a product remotely but a non-empty slug under the tax classes endpoint. Because the tax class could be either an empty string or "standard" while they represent the same tax class, we didn't account this fully when comparing the latest product against the original product when navigating away.

steps to repro:

Prerequisite: the simple product has a standard tax class (thus the product has tax class as an empty string from the API)
- Go to the Products tab
- Tap on the simple Product in the prerequisite
- Tap Price
- Update the regular price to a different value
- Tap "Done"
- Tap Price again
- Tap "<" in the navigation bar --> now the discard changes action sheet comes up without any updates

```
original: "standard"
new: ""
```

### Inventory settings

Similarly, it was caused by a property that could be represented by multiple values. In this case, it was `stockQuantity` that is set to `nil` after saving a Product with stock management disabled. We should compare the stock quantity only when the stock management is enabled.

```
original: nil
new: 0
```

**Comment by jaclync** [comment] 2020-03-18 02:06
fixed in https://github.com/woocommerce/woocommerce-ios/pull/1979, closing for now!

**Closed by jaclync** 2020-03-18 02:06 UTC
Labels: Add/Edit Products, [Type] Bug
