### ISSUE TITLE
Store list doesn't refresh automatically; needs a re-login to refresh

### ISSUE THREAD

**Issue by arunsathiya** [woocommerce/woocommerce-ios#1040] opened 2019-06-17 16:58 UTC
**Describe the bug**

When I use the `Switch store` button on the app, I would expect the list to show only the stores that have Jetpack connected and activated. Any old sites without Jetpack should be removed when I visit the `Switch store` list.

That does not happen, and requires a re-login to show the updated, proper list.

**To Reproduce**

- Launch the WooCommerce iOS app.
- Click on `My store` tab at the bottom left.
- Click on the settings gear at the top right.
- Click on `Switch store` button

**Screenshots**

NA

**Expected behavior**

The list of stores shown on this view are the only ones that have Jetpack connected and activated.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**

- Device: iPad Air 2019 edition.
- iOS version: 12.3.1
- WooCommerce iOS version: 2.0 (2.0.0.1)

**WordPress Environment**

NA

**Notes**

On the Android app, visiting the store switcher refreshes the list automatically. There is no requirement to re-login.

**Comment by mindgraffiti** [comment] 2019-06-17 17:09
Duplicate of High-Priority bug found here: #931. Using the "Switch Store" feature doesn't automatically call the list of sites and do a refresh, which is root problem here.

**Closed by mindgraffiti** 2019-06-17 17:09 UTC
Labels: [Type] Enhancement
