### ISSUE TITLE
Add Unit Tests for checkCardPresentPaymentEligibility in OrderDetailsViewModel

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-ios#7064] opened 2022-06-09 15:17 UTC
**Describe the bug**

On this [PR](https://github.com/woocommerce/woocommerce-ios/pull/7063) we removed the unit tests relative to  `checkCardPresentPaymentEligibility` in https://github.com/woocommerce/woocommerce-ios/pull/7063/commits/902cfd1454539cdd535e664803ae8b4f01d53e06 because we couldn't inject/mock the configuration loader. To keep that PR small, I create this issue to accomplish that.

## Tasks

- Make the `configurationLoader` task injectable in `OrderDetailsViewModel`
- Create a mock for that
- Add unit tests depending on the different country case (see `SimplePaymentsMethodsViewModelTests`)

**Comment by iamgabrielma** [comment] 2022-08-05 06:24
Hi @toupper! While checking this issue again, I'm a bit confused of what we should test or mock, and I wonder if the issue is still valid since was created, as had been a bunch of changes. Let me know if I missed something or I'm reading it wrong, but as far as I understand the current setup:

- [CardPresentPaymentTests](https://github.com/woocommerce/woocommerce-ios/blob/375b2e5badccd9bca49a969a635597cd6a55cd3c/Yosemite/YosemiteTests/Stores/Order/Order%2BCardPresentPaymentTests.swift) is already testing card present payment eligibility by using `Order.CardPresentPaymentsConfiguration` as SUT in the assertions.

- Creating a `Mock` for `CardPresentPaymentsConfiguration` doesn't seem to give us much value as this has a `self.init()` that already creates the object with all values for us, based uniquely in the country that is passed as a parameter, as we do not pass any other variable. 

- This `self.init()` implementation is also tested separately in [CardPresentConfigurationTests](https://github.com/woocommerce/woocommerce-ios/blob/ba4e365b77b1aa53f4ed3c897571ade7fe4404a0/Yosemite/YosemiteTests/Model/CardPresentConfigurationTests.swift).

Because of these I believe we can close this issue at the moment, but let know if I missed anything :)

**Comment by iamgabrielma** [comment] 2022-08-18 12:57
Discussed this one with @toupper in a pairing session and indeed seems that this issue is currently out of date. Closing.

**Closed as completed by iamgabrielma** 2022-08-18 12:57 UTC
Labels: type: task, type: technical debt, feature: mobile payments, feature: order creation
