### ISSUE TITLE
Crash when I press the Log Out button

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1947] opened 2020-03-12 15:39 UTC
I encountered a strange crash when I press the Log Out button. It seems related to Core Data, but redoing 
## Strackstrace:
```
2020-03-12 16:26:03.090965+0100 WooCommerce[15269:355424] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Object's persistent store is not reachable from this NSManagedObjectContext's coordinator'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreData                            0x00007fff2384295c -[_NSCoreManagedObjectID _isPersistentStoreAlive] + 0
	3   CoreData                            0x00007fff2382ea98 -[NSManagedObjectContext objectWithID:] + 543
	4   CoreData                            0x00007fff2387d13a _faultBatchAtIndex + 2740
	5   CoreData                            0x00007fff2387eb5e -[_PFBatchFaultingArray retainedObjectAtIndex:] + 74
	6   CoreData                            0x00007fff2387ec2d -[_PFBatchFaultingArray objectAtIndex:] + 44
	7   libswiftCore.dylib                  0x00000001050d7ace $ss12_ArrayBufferV19_getElementSlowPathyyXlSiF + 142
	8   libswiftCore.dylib                  0x00000001050daa1a $sSayxSicir + 202
	9   libswiftCore.dylib                  0x00000001050db118 $sSayxGSlsSly7ElementQz5IndexQzcirTW + 56
	10  libswiftCore.dylib                  0x000000010511501c $ss16IndexingIteratorVyxGStsSt4next7ElementQzSgyFTW + 460
	11  libswiftCore.dylib                  0x000000010521e60d $sSTsE10compactMapySayqd__Gqd__Sg7ElementQzKXEKlF + 557
	12  Yosemite                            0x00000001049e215e $s8Yosemite17ResultsControllerC14fetchedObjectsSay12ReadOnlyTypeQzGvg + 558
	13  WooCommerce                         0x00000001012e1c76 $s11WooCommerce26ShippingProvidersViewModelC015storeCountryHasD033_B2A729B1049D9ADAB13B99803C294E13LLSbvg + 54
	14  WooCommerce                         0x00000001012e3581 $s11WooCommerce26ShippingProvidersViewModelC5delta33_B2A729B1049D9ADAB13B99803C294E13LLSiyF + 49
	15  WooCommerce                         0x00000001012e3483 $s11WooCommerce26ShippingProvidersViewModelC16numberOfSectionsSiyF + 131
	16  WooCommerce                         0x0000000101039a53 $s11WooCommerce31ShipmentProvidersViewControllerC16numberOfSections2inSiSo07UITableE0C_tF + 51
	17  WooCommerce                         0x0000000101039aa4 $s11WooCommerce31ShipmentProvidersViewControllerC16numberOfSections2inSiSo07UITableE0C_tFTo + 68
	18  UIKitCore                           0x00007fff482a3517 -[UITableView _numberOfSections] + 75
	19  UIKitCore                           0x00007fff482b64e1 -[UITableViewRowData _updateNumSections] + 31
	20  UIKitCore                           0x00007fff482b6c53 -[UITableViewRowData invalidateAllSections] + 59
	21  UIKitCore                           0x00007fff48254f5f -[UITableView _updateRowData] + 185
	22  UIKitCore                           0x00007fff4827368d -[UITableView noteNumberOfRowsChanged] + 96
	23  UIKitCore                           0x00007fff4827211d -[UITableView reloadData] + 1426
	24  UIKit                               0x00000001079fc5b4 -[UITableViewAccessibility reloadData] + 44
	25  WooCommerce                         0x0000000101039a04 $s11WooCommerce31ShipmentProvidersViewControllerC09configureE5Model33_1D3135596F92F37301E2B100299E0343LLyyFyycfU_ + 452
	26  WooCommerce                         0x00000001012e296e $s11WooCommerce26ShippingProvidersViewModelC14dataWasUpdated33_B2A729B1049D9ADAB13B99803C294E13LLyyF + 174
	27  WooCommerce                         0x00000001012e2a52 $s11WooCommerce26ShippingProvidersViewModelC26configureResultsControlleryyFyycfU0_ + 194
	28  Yosemite                            0x00000001049e406f $s8Yosemite17ResultsControllerC15storageWasResetyyF + 543
	29  Yosemite                            0x00000001049e411a $s8Yosemite17ResultsControllerC15storageWasResetyyFTo + 42
	30  CoreFoundation                      0x00007fff23b9b5bc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	31  CoreFoundation                      0x00007fff23b9aa35 _CFXRegistrationPost1 + 421
	32  CoreFoundation                      0x00007fff23b9a7a1 ___CFXNotificationPost_block_invoke + 193
	33  CoreFoundation                      0x00007fff23c988b3 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1811
	34  CoreFoundation                      0x00007fff23b9a0f6 _CFXNotificationPost + 950
	35  Foundation                          0x00007fff2574bbf7 -[NSNotificationCenter postNotificationName:object:userInfo:] + 59
	36  Storage                             0x0000000104b90c93 $s7Storage15CoreDataManagerC5resetyyFyyXEfU_ + 1395
	37  Storage                             0x0000000104b910fc $sIg_Ieg_TR + 12
	38  Storage                             0x0000000104b91121 $sIeg_IyB_TR + 17
	39  CoreData                            0x00007fff23836e36 developerSubmittedBlockToNSManagedObjectContextPerform + 154
	40  CoreData                            0x00007fff23836d1d -[NSManagedObjectContext performBlockAndWait:] + 197
	41  Storage                             0x0000000104b90676 $s7Storage15CoreDataManagerC5resetyyF + 566
	42  WooCommerce                         0x000000010131a8f9 $s11WooCommerce20DefaultStoresManagerC14deauthenticateAA0dE0_pyF + 537
	43  WooCommerce                         0x000000010131af48 $s11WooCommerce20DefaultStoresManagerCAA0dE0A2aDP14deauthenticateAaD_pyFTW + 24
	44  WooCommerce                         0x000000010106e3e4 $s11WooCommerce22SettingsViewControllerC10logOutUser33_4DA95ECAB80812ABDA8BECB9ACE70800LLyyF + 164
	45  WooCommerce                         0x000000010106e32d $s11WooCommerce22SettingsViewControllerC16logoutWasPressed33_4DA95ECAB80812ABDA8BECB9ACE70800LLyyFySo13UIAlertActionCcfU0_ + 445
	46  WooCommerce                         0x0000000100f21ba6 $sSo13UIAlertActionCIegg_ABIeyBy_TR + 70
	47  WordPressUI                         0x0000000103de9cc9 $sSo13UIAlertActionCIeyBy_ABIegg_TR + 25
	48  WordPressUI                         0x0000000103de9a46 $sSo13UIAlertActionCIegg_ABIeyBy_TR + 70
	49  WordPressUI                         0x0000000103de9cc9 $sSo13UIAlertActionCIeyBy_ABIegg_TR + 25
	50  WordPressUI                         0x0000000103de9a46 $sSo13UIAlertActionCIegg_ABIeyBy_TR + 70
	51  UIKitCore                           0x00007fff476331b1 -[UIAlertController _invokeHandlersForAction:] + 105
	52  UIKitCore                           0x00007fff47633b89 __103-[UIAlertController _dismissAnimated:triggeringAction:triggeredByPopoverDimmingView:dismissCompletion:]_block_invoke.458 + 16
	53  UIKitCore                           0x00007fff4792013c -[UIPresentationController transitionDidFinish:] + 978
	54  UIKitCore                           0x00007fff47924c78 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.503 + 199
	55  UIKitCore                           0x00007fff47a3df47 -[_UIViewControllerTransitionContext completeTransition:] + 88
	56  UIKitCore                           0x00007fff4856b908 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 671
	57  UIKitCore                           0x00007fff4853bf31 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 268
	58  UIKitCore                           0x00007fff4853c4a3 -[UIViewAnimationState animationDidStop:finished:] + 259
	59  UIKit                               0x0000000107a8378a -[UIViewAnimationStateAccessibility animationDidStop:finished:] + 118
	60  UIKitCore                           0x00007fff4853c62a -[UIViewAnimationState animationDidStop:finished:] + 650
	61  UIKit                               0x0000000107a8378a -[UIViewAnimationStateAccessibility animationDidStop:finished:] + 118
	62  QuartzCore                          0x00007fff2b14496c _ZN2CA5Layer23run_animation_callbacksEPv + 306
	63  libdispatch.dylib                   0x0000000105bb9d48 _dispatch_client_callout + 8
	64  libdispatch.dylib                   0x0000000105bc7de6 _dispatch_main_queue_callback_4CF + 1500
	65  CoreFoundation                      0x00007fff23bd4049 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	66  CoreFoundation                      0x00007fff23bceca9 __CFRunLoopRun + 2329
	67  CoreFoundation                      0x00007fff23bce066 CFRunLoopRunSpecific + 438
	68  GraphicsServices                    0x00007fff384c0bb0 GSEventRunModal + 65
	69  UIKitCore                           0x00007fff48092d4d UIApplicationMain + 1621
	70  WooCommerce                         0x0000000101197081 main + 497
	71  libdyld.dylib                       0x00007fff5227ec25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

## Steps to reproduce the behavior:
1. Navigate to orders
2. Navigate to an order detail in `processing` status
3. Press Add Tracking
4. Select a carrier
5. Press dismiss
6. Go to app settings
7. Press the Log out button and press Log Out on the alert
8. You will see the crash

## Mobile Environment
- Device: iPhone 11 Pro Simulator
- iOS version: 13.3
- WooCommerce iOS version: 3.8 (develop)

**Comment by shiki** [comment] 2020-07-27 19:17
This is a duplicate of #2251. I'm closing this one since #2251 has a Sentry link.

**Closed by shiki** 2020-07-27 19:17 UTC
Labels: [Type] Crash
