### ISSUE TITLE
Log in flow: Choosing "Try another account" shows spinner forever

### ISSUE THREAD

**Issue by eshurakov** [woocommerce/woocommerce-ios#3270] opened 2020-12-02 11:51 UTC
**Describe the bug**
Choosing "Try another account" on the last step of log in flow completely blocks the app. The app can be used again only after force restarting it.

**To Reproduce**
1. Request on magic link and tap on it in the email
2. Tap "Try another account"
3. See "white" screen and a spinner. The app is now stuck on this screen

**Screenshots**
![IMG_0012](https://user-images.githubusercontent.com/54751/100869060-c6d01400-349c-11eb-8c3b-96045bb743a4.PNG)

**Expected behavior**
Restart the log in flow

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone and iPad
- iOS version: 14.2
- WooCommerce iOS version: 5.6

**Comment by shiki** [comment] 2020-12-02 15:46
@ctarda Is this something that will be fixed with the UL project?

**Comment by ctarda** [comment] 2020-12-03 02:57
@shiki not per se. I think we should fix this independently from UL

**Comment by rachelmcr** [comment] 2020-12-17 11:26
Thanks for this report! I missed it and opened a duplicate in https://github.com/woocommerce/woocommerce-ios/issues/3367, but I'm going to go ahead and close this issue since the other one already has notes from researching the cause.

**Closed as completed by rachelmcr** 2020-12-17 11:26 UTC
Labels: type: bug, feature: login
