### ISSUE TITLE
Unit Tests: Intermittent crash on ...

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1159] opened 2019-08-02 17:04 UTC
Ref. p99K0U-1wF-p2 (see stack trace here)

The crash is in `String+HTML` in `htmlToAttributedString`, and is happening when running the test `StringHTMLTests.testHexaCharactersAreConvertedIntoSimpleCharacters`

**Comment by ctarda** [comment] 2019-08-25 22:11
This does not seem to be happening anymore. At least, for me, it has not happened at all in the last week, when in the past, it used to happen almost every time I run the tests. I am going to close it.

**Comment by ctarda** [comment] 2019-08-25 22:12
Closing as unable to reproduce

**Closed by ctarda** 2019-08-25 22:12 UTC
Labels: Unit Tests, [Type] Bug
