### ISSUE TITLE
Notifications are not delivered after logging out and logging back in

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce-ios#763] opened 2019-03-11 14:40 UTC
**Describe the bug**
Notifications no longer work, supposedly after logging out which makes the device un-register for push notifications, and logging back in. There's no second *request to Apple* to register for push notifications

**To Reproduce**
I wasn't able to reproduce this by logging out and logging back in multiple times. @mindgraffiti suggested a bug report here since he's reviewed the code.

**Screenshots**

This is the app log from 1752912-zen:

Dotcom Push Notifications Registration Failure: Optional(Dotcom Error: [invalid_device_token] Invalid device token.)
2019/01/27 17:36:54:334  <> Mapping Error: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "name", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))
2019/01/27 17:36:54:335

**Expected behavior**
The notifications should work regardless logging out/logging back in

**Mobile Environment**
Please include:
Not available

**Comment by mindgraffiti** [comment] 2019-03-11 14:58
This is not steps to reproduce, these are steps reported by the user's activity log.

1. user logs out
2. user logs back in
3. SSR reports successful DotCom push notification unregistration
4. new DotCom push notification registration initiated 

Step 4 should have made a new request to Apple? Without that step, it looks like the device token is nil, which would explain why the DotCom registration fails.

The other anomaly is that the user's SSL cert is either missing or server-side SSL fails before the log out, causing Jetpack API requests to fail. Not sure it is related to the APNs register / unregister, but that might be affecting the order that API requests are made or affecting API requests getting skipped.

relevant parts from app log:

```
2019/01/27 17:36:54:292  📱 Successfully unregistered from WordPress.com Push Notifications!
2019/01/27 17:36:54:294  ⛔️ Dotcom Push Notifications Registration Failure: Optional(Dotcom Error: [invalid_device_token] Invalid device token.)
2019/01/27 17:36:54:334  <> Mapping Error: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "name", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))
2019/01/27 17:36:54:335  ⛔️ Dashboard (Top Performers) — Error synchronizing top earner stats: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "name", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))
```

**Comment by mindgraffiti** [comment] 2019-03-14 21:05
The user reported that the ka-ching sound is working again. I researched the bug and it looks like they either disconnected Jetpack or had SSL issues with the site, which caused all kinds of errors to pop up in the activity log. Closing this issue as it doesn't appear to be an app bug after all.

**Closed by mindgraffiti** 2019-03-14 21:05 UTC
Labels: Notifications, [Type] Bug
