### ISSUE TITLE
Height of `AddProductWithAIActionSheet` is wrong

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#12604] opened 2024-04-29 15:54 UTC
It appears that whenever we present the `AddProductWithAIActionSheet`, the vertical size is consistently incorrect, resulting in some extra space at the bottom.

<img src="https://github.com/woocommerce/woocommerce-ios/assets/495617/d9fe094e-dfae-4da1-a570-3ee2a5352549" width=300 />

**Comment by pmusolino** [comment] 2024-04-29 15:54
On it

**Comment by dangermattic** [comment] 2024-04-29 15:54
Thanks for reporting! 👍

**Comment by rachelmcr** [comment] 2024-08-28 15:34
Closing as duplicate of https://github.com/woocommerce/woocommerce-ios/issues/11211.

**Closed as completed by rachelmcr** 2024-08-28 15:34 UTC
Labels: type: bug, feature: add/edit products
