### ISSUE TITLE
"Try collecting payment again" Button Does Not Do Anything

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#4547] opened 2021-07-05 23:01 UTC
I'm not sure what should happen with this. I tried to collect payment for an order that has $0. Somewhat expectedly, the payment failed. When I press the “Try collecting payment again“ button, the dialog is dismissed 

https://user-images.githubusercontent.com/198826/124522944-33ecb480-ddb2-11eb-8b8b-6803ae636968.mp4

## Steps

1. Navigate to an order that has $0 amount. In this case, the order had 0 EURO but the site is now in USD. Weird, I know. 😄 But this is probably what causes the error. 
2. After the error is shown, tap on “Try collecting payment again”. Nothing happens. 

## Expectations

Maybe something should happen? The collect payment screen should probably be shown again?

**Comment by koke** [comment] 2021-07-06 07:45
I tested this on `develop` and I couldn't reproduce exactly. Tapping on the retry button does retry, although it just ends in a different error. I think we should disable the Collect Payment button if the quantity is 0, unless until we support charging for arbitrary amounts.

https://user-images.githubusercontent.com/8739/124561965-c3d84000-de3e-11eb-8f63-5dfed98f1419.MP4

**Comment by koke** [comment] 2021-07-06 07:59
Also leaving a note here that we might want to re-think how we track what has been paid so far. If I disable the Collect Payment button for $0 orders, the order screen will then show the Refund button instead, which also doesn't make sense 🤷🏽‍♂️

**Comment by shiki** [comment] 2021-07-06 14:01
It's very likely that this is just nitpicking, very low priority, and should just be closed. I just thought of reporting in case it resonates with you all and brings up underlying issues. 🙃

**Comment by koke** [comment] 2021-07-06 14:06
I just realized it was a duplicate of #4254, which was just fixed by #4554 🎉

**Closed as completed by koke** 2021-07-06 14:06 UTC
Labels: type: bug, feature: mobile payments

**Comment by shiki** [comment] 2021-07-06 14:08
💥
