### ISSUE TITLE
Some order status' get clipped

### ISSUE THREAD

**Issue by rezzap** [woocommerce/woocommerce-ios#1801] opened 2020-01-30 14:04 UTC
**Describe the bug**
The order status button gets clipped on iPhone 11 Pro Max and isn't fully visible on certain orders from the Order page. 

Reported by a user in 2665710-zen

**To Reproduce**
1. Go to the latest version of the Woo App
2. Click on Orders
3. Look for the order status when multiple items are added. 
4. See some of these are clipped. 

The user's interface is in Russian, so I'm not sure if this related or not. 

**Screenshots**
![Woo app1](https://user-images.githubusercontent.com/10325627/73456010-06a00980-4369-11ea-8fd5-4212e58d234d.png)
![Woo app2](https://user-images.githubusercontent.com/10325627/73456015-0869cd00-4369-11ea-9ca8-27d0607c7ca5.png)

**Expected behavior**
I would expect all order status' to be fully visible.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 11 Pro Max
- iOS version: 13.3.1
- WooCommerce iOS version: 3.4

**WordPress Environment**
<details>
```
Can request SSR from the user if needed. 
```
</details>

**Comment by pmusolino** [comment] 2020-01-30 14:19
In release 3.5 (which is not the version used by the user) I'm not able to reproduce the issue. Maybe this implementation https://github.com/woocommerce/woocommerce-ios/pull/1755 of @shiki already fixed this bug?

**Comment by shiki** [comment] 2020-02-05 14:20
I can confirm that there is some clipped text in Woo 3.4. After #1755, it doesn't happen anymore. 

Woo 3.4  | #1755 
--------|-------
<img width="545" alt="before" src="https://user-images.githubusercontent.com/198826/73849691-93264e00-47e7-11ea-8e30-9f039af8bb14.png">|       <img width="545" alt="after" src="https://user-images.githubusercontent.com/198826/73849692-93264e00-47e7-11ea-9327-6fab7d0484d0.png">

We can consider this as fixed. It will be released on Woo 3.5. 

Thank you for the report, @rezzap!

**Comment by shiki** [comment] 2020-02-05 21:18
Actually, I was wrong. 😭 It can still sometimes happen if there are 2 lines for the Order # + Name. This only happens when you first open the Orders tab. Scrolling the table view will fix them eventually. 

<img src="https://user-images.githubusercontent.com/198826/73883873-ef0dc880-4821-11ea-9215-b3e1a6b93665.png" width="240">

Reopening this. Sorry for the false report!

**Closed** 2020-03-11 11:36 UTC
Labels: Order List, [Type] Bug
