### ISSUE TITLE
Native Jetpack installation fails for JCP JN sites

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#8542] opened 2023-01-04 05:28 UTC
### Description

Native Jetpack installation fails for JCP JN sites.

### Steps to reproduce

Prerequisites
1. Create a JN site.
2. Install WooCommerce 
3. Install the WooCommerce payments plugin. You can skip the authorization with the WPCOM account part.

From mobile app
- Log out of the app or skip login onboarding if needed.
- On the prologue screen, select "Log In" or "Continue with WordPress.com" based on the A/B test variant you get.
- Log in with your WordPress.com account.
- If your account doesn't have any associated site, notice that the empty store picker is displayed with the matching design as on Figma.
- Select Add a Store > Connect an existing site.
- Enter the address of your test store and tap Continue.
- You should see a Jetpack error screen from where you can Install Jetpack or Connect Jetpack natively.
- Tap on the `Connect Jetpack` button, and you will end up in a `404` error screen.

### Screenshots
| Screen | Image |
| --- | --- |
| Start connection | <img src="https://user-images.githubusercontent.com/524475/210489853-a3bf01d6-1785-455c-9176-b63c4f08776f.png" width="300"/>  | 
| `404` error | <img src="https://user-images.githubusercontent.com/524475/210489850-b9b8e912-0a9f-4a66-932d-527b6704163d.png" width="300"/>  |

**Comment by pmusolino** [comment] 2023-02-27 16:31
This could be helpful to know for @itsmeichigo (but probably she is already aware of this)

**Comment by itsmeichigo** [comment] 2023-02-28 03:54
Thanks for reporting @selanthiraiyan  - did you happen to have more information about the error? I.e which request it was? And is the error consistent for your site?

**Comment by selanthiraiyan** [comment] 2023-02-28 04:04
- Jaclyn reported this issue [during a PR review](https://github.com/woocommerce/woocommerce-ios/pull/8533#pullrequestreview-1235303173). 
- From the PR description, it looks like this happened for all JCP sites. I don't remember any other details about this.

**Comment by itsmeichigo** [comment] 2023-04-04 03:44
Potential cause: p1680512610989549-slack-CBG1CP4EN.
I will test this again after the issue is fixed on the backend.

**Comment by itsmeichigo** [comment] 2023-10-09 00:58
The issue has been fixed on WCPay side [p1696626882601429/1680512610.989549-slack-CBG1CP4EN]. I tested and confirmed that Jetpack installation & activation works correctly now.

**Closed as completed by itsmeichigo** 2023-10-09 00:58 UTC
Labels: type: bug, feature: login
