### ISSUE TITLE
Localization: Prices throughout the app are rounded to whole numbers in some UI languages

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1756] opened 2020-01-21 18:03 UTC
**Describe the bug**

In some UI languages, prices (e.g. order totals, order details, product prices) are rounded to whole numbers instead of showing an accurate amount.

In my testing, languages such as Spanish, German, French, and Dutch reproduce the issue while other languages such as English, Arabic, and Japanese do not.

**To Reproduce**

1. Create an order with an order total that is not a whole number (e.g. `$12.34`).
2. In the Settings app > Woo > Language set the language to English.
3. Open the Woo app and confirm that the new order appears with the correct order total ($12.34).
4. In the Settings app > Woo > Language set the language to Spanish or German.
5. Open the Woo app and notice that the order total is now incorrect ($12.00 instead of $12.34).

You can switch UI languages and see the same symptoms elsewhere in the app, e.g. order details or the prices on each product on the Products tab.

**Screenshots**

Correct amount in English:

<img src="https://user-images.githubusercontent.com/8658164/72830275-46cfff80-3c78-11ea-8575-5af43948b68f.png" width="50%">

Incorrect amount in German:

<img src="https://user-images.githubusercontent.com/8658164/72830277-48012c80-3c78-11ea-9067-64277119d6e8.png" width="50%">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3
- WooCommerce iOS version: 3.4.0.1 TestFlight beta

Original report from a TestFlight beta tester using iPhone 7 Plus with iOS 13.3.

**Comment by rachelmcr** [comment] 2020-01-21 18:07
@pmusolino Could this be related to changes you made recently to the currency formatter?

**Comment by pmusolino** [comment] 2020-01-21 20:17
Thanks @rachelmcr for discovering this. I verified, and yes seems that there was a regression (but unit tests are green).
I'm investigating why this happens. Do you think that we can push the hotfix in release 3.4?

**Comment by rachelmcr** [comment] 2020-01-22 11:20
Thanks for the quick fix! @jkmassel can we get another WCiOS 3.4 beta release with this fix?

**Comment by jkmassel** [comment] 2020-01-22 15:56
We sure can – LMK when it's merged and I'll be happy to ship it!

**Comment by pmusolino** [comment] 2020-01-22 15:57
Thanks @jkmassel, it's already merged https://github.com/woocommerce/woocommerce-ios/pull/1758

**Comment by pmusolino** [comment] 2020-01-22 15:58
I'm closing this since the fix was merged in branch 3.4.

**Closed by pmusolino** 2020-01-22 15:58 UTC
Labels: Localization, [Type] Bug
