### ISSUE TITLE
Products with a decimal number don't display order details for quantity

### ISSUE THREAD

**Issue by rossanafmenezes** [woocommerce/woocommerce-ios#3494] opened 2021-01-19 14:30 UTC
**Describe the bug**

Much like this issue here in the Android Repo [2838](https://github.com/woocommerce/woocommerce-android/issues/2838) this user has an extension to show the order quantity of a product in decimal. When they open the app it shows a message saying that "it was impossible to connect to the store" and you cannot access any data through the app, it's not only affecting the info of that
product but any data of the whole store. And when they change back the stock to a non-decimal value, the problem disappears.

**To Reproduce**

1 - Install WPC Product Quantity for WooCommerce (user has the Premium one but I tested with the regular version and was able to reproduce the issue
2 -   Go to a non-virtual product inventory
3 - add a decimal value to the inventory (I changed from 6 to 600.5)
4 - Go to the app and try to refresh the product screen

![Screenshot 2021-01-19 at 9 09 20 AM](https://user-images.githubusercontent.com/30724184/105046237-d7315380-5a36-11eb-85d0-60345bc547bf.png)

![IMG_0026](https://user-images.githubusercontent.com/30724184/105046264-e0babb80-5a36-11eb-9edf-32249082f4d2.jpg)

See the unable to Refresh message at the bottom. Got this message all across the app. 

Once you change the inventory back to a whole number the message disappears and the app refreshes and show the new inventory number (600 in this case)

![Screenshot 2021-01-19 at 9 09 26 AM](https://user-images.githubusercontent.com/30724184/105046555-3d1ddb00-5a37-11eb-9a3e-27248c541ec0.png)

![IMG_0027](https://user-images.githubusercontent.com/30724184/105046631-54f55f00-5a37-11eb-9597-a56e45b2454e.jpg)

**Expected behavior**

The product should be displayed on the order details screen with the correct product quantity in decimal.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:

- Device: iPad 7th Generation
- iOS version: 14.2
- WooCommerce iOS version: 5.4.0.2 (before updating) and 5.7.0.3

User's info
3655729-zen
 IOS version is 13.1.3
User Woo version 5.6.0.2

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://rfma8cbusiness.wpcomstaging.com
Site address (URL): https://rfma8cbusiness.wpcomstaging.com
WC Version: 4.9.0
REST API Version: ✔ 4.9.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.26
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.74.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.0
WC Database Prefix: wp_
Total Database Size: 4.96MB
Database Data Size: 3.39MB
Database Index Size: 1.57MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_csp3_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_email_log: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.03MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.27MB + Index: 0.06MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_vikbooking_adultsdiff: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_busy: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_characteristics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_config: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_countries: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_coupons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_cronjobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_custfields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_customers_orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_dispcost: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_einvoicing_config: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_einvoicing_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_fests_dates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_gpayments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_invoices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_iva: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_operators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_optionals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_orderhistory: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_ordersbusy: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_ordersrooms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_packages_rooms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_prices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_receipts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_restrictions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_rooms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_seasons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_texts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_tmplock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_trackings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_tracking_infos: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_translations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vikbooking_wpshortcodes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

amp_validated_url: 1
attachment: 17
customize_changeset: 6
jetpack_migration: 2
jp_img_sitemap: 3
jp_pay_product: 1
jp_sitemap: 3
jp_sitemap_master: 3
nav_menu_item: 6
oembed_cache: 1
page: 13
post: 14
product: 4
product_variation: 4
revision: 35
seedprod: 1
shop_order: 15
shop_order_refund: 1
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

Akismet Anti-Spam: by Automattic – 4.1.8
AMP: by AMP Project Contributors – 2.0.10
Code Snippets: by Code Snippets Pro – 2.14.0
Coming Soon Page, Maintenance Mode & Landing Pages by SeedProd: by SeedProd – 6.0.10.1
Email Log: by Sudar – 2.4.3
WordPress.com Editing Toolkit: by Automattic – 2.11
Jetpack by WordPress.com: by Automattic – 9.3.2
Slides & Presentations: by Ella van Durpe – 0.0.39
WooCommerce Stripe Gateway: by WooCommerce – 4.7.0
WooCommerce Shipping & Tax: by Automattic – 1.25.5
WooCommerce: by Automattic – 4.9.0
WPC Product Quantity for WooCommerce: by WPClever.net – 1.5.0

### Inactive Plugins (11) ###

Classic Editor: by WordPress Contributors – 1.6
CoBlocks: by GoDaddy – 2.6.0
Elementor: by Elementor.com – 3.0.16
Gutenberg: by Gutenberg Team – 9.7.4
Hello Dolly: by Matt Mullenweg – 1.7.2
Insert Headers and Footers: by WPBeginner – 1.5.0
Layout Grid: by Automattic – 1.3
Page Optimize: by Automattic – 0.5.1
Smash Balloon Instagram Feed: by Smash Balloon – 2.6.2
VikBooking: by E4J s.r.l. – 1.3.11
Yoast SEO: by Team Yoast – 15.6.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #97 - /shop/
Cart: #98 - /cart/
Checkout: #99 - /checkout/
My account: #100 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Canard
Version: 1.0.12-wpcom
Author URL: https://wordpress.com/themes/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/wpc-product-quantity/templates/quantity-input.php

### Action Scheduler ###

Complete: 16
Oldest: 2020-12-29 14:10:01 +0000
Newest: 2021-01-18 13:46:59 +0000

`
```
</details>

**Comment by ctarda** [comment] 2021-01-19 14:37
Thanks for the thorough report @rossanafmenezes 🙇

**Comment by rachelmcr** [comment] 2021-01-22 18:20
I took a quick look at this and confirmed the error is that the app expects integer values for stock quantity:

```
⛔️ Error synchronizing products: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "stock_quantity", intValue: nil)], debugDescription: "Parsed JSON number <505.5> does not fit in Int64.", underlyingError: nil))
```

We can treat quantity as a decimal, similar to what we did in https://github.com/woocommerce/woocommerce-ios/issues/662. We'll need to make this change for both Product and ProductVariation. (In Core Data the `stockQuantity` attribute type for Product is a string, but for ProductVariation it's Int64 so that will need to be changed.)

**Comment by shiki** [comment] 2021-02-01 19:06
Discussed in p91TBi-4iF-p2. We would need changes in the API to support this.

**Comment by rachelmcr** [comment] 2021-02-23 16:30
As noted above, we would need API changes to fully support editing decimal stock quantities in the app.

However, the changes in #3705 and #3717 will resolve the bug where products weren't loading at all. This makes it possible to load the product list if some products have have decimal stock quantities, and displays product or variation's Inventory settings as read-only if it has a decimal stock quantity. (Other settings and integer stock quantities can still be edited as usual.)

**Comment by shiki** [comment] 2021-02-23 18:37
Thank you, Rachel! 

I'll close this issue since we fixed the product loading problem. Specific support for WPC Product Quantity and other related plugins is best tracked in the [Ideas Board](https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=84283).

**Closed as completed by shiki** 2021-02-23 18:37 UTC
Labels: type: bug, feature: order details, needs: api support, good first issue, impact: high
