### ISSUE TITLE
Order Details: tapping on a Product doesn't open the correct Product due to a glitch in the tableview

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1841] opened 2020-02-07 11:41 UTC
If an Order has multiple Products, tapping on a Product the first time do the right thing, but if you go back and you tap another product (without scrolling the content), the table view undergoes a glitch and makes you select the unwanted product.

It happens both enabling the Refunds flag and without.

![bug products selection](https://user-images.githubusercontent.com/495617/74025872-36709200-49a5-11ea-8799-7f29d325b880.gif)

**Mobile Environment**
Please include:
- Device: Simulator iPhone 11 Pro
- iOS version: 13.2.2
- WooCommerce iOS version: develop

I was not able to replicate the bug on Woo 3.5 on iPhone X with iOS 13.3

**Comment by jaclync** [comment] 2020-03-20 02:36
is this similar to this issue https://github.com/woocommerce/woocommerce-ios/issues/1839 that was fixed in release 3.6?

**Comment by pmusolino** [comment] 2020-03-20 14:17
@jaclync it seems similar, but I confirm that it's also present in our release 3.8.

**Comment by joshheald** [comment] 2022-05-23 15:38
I can't reproduce this any more. @pmusolino feel free to re-open if you can 😊

**Closed by joshheald** 2022-05-23 15:38 UTC
Labels: type: bug, feature: order details, feature: refunds
