### ISSUE TITLE
Shipping Labels: No items is found on Package Details screen when creating a shipping label the first time

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#6565] opened 2022-04-05 03:20 UTC
**Describe the bug**
When first logging in to a store and creating a shipping label immediately, the Package Details screen shows no item at all. Tapping back and navigating to the Package Details screen again helps with showing the list of items.

**To Reproduce**
1. Log out of your account if already logged in.
2. Log back in and select the store with an order that is eligible for creating shipping labels.
3. Navigate to Orders tab, select the order and proceed to create a shipping label for the order.
4. Proceed through the Ship from and Ship to fields and select Package Details. Notice that no item is listed here, and a (!) icon is displayed.
5. Tap "<" to get back to the form and select Package Details again. The items in the order should now be listed properly. 

**Screenshots**
<img src="https://user-images.githubusercontent.com/5533851/161672068-3780021a-ce49-4c0e-9caf-02235aae7e5e.png" width=320 />

**Expected behavior**
The list of items should always be displayed on the Package Details screen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 12 Pro
- iOS version: 15.4
- WooCommerce iOS version: 8.9

**Comment by rachelmcr** [comment] 2023-01-18 17:21
I was testing shipping labels again and couldn't reproduce this issue with the steps here. Even after a fresh login, the Package Details screen loaded all of the details as expected. Is it ok to close this issue or is this still reproducible under certain conditions?

I tested with:

- Device: iPhone 12 Mini
- iOS version: 16.2
- WooCommerce iOS version: 11.9.0.0 (TestFlight beta)

**Comment by itsmeichigo** [comment] 2023-01-20 09:30
I haven't tested again for a long time - the last time I checked, the issue was not consistent either. But please feel free to close this issue if you cannot reproduce it, we can always reopen this if the issue ever comes up again.

**Closed as completed** 2023-01-20 11:19 UTC
Labels: type: bug, feature: shipping labels
