### ISSUE TITLE
Products: Loading skeleton is incomplete on first load

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#3112] opened 2020-11-09 16:15 UTC
**Describe the bug**

As @ThomazFB reported (internal ref: p5T066-1Bt-p2#comment-6253):

When we first open the app and go directly to the Products section the loading skeleton shows up incomplete, only the image part is glowing, meanwhile, the rest is blank.

![image](https://user-images.githubusercontent.com/8658164/98566154-591e3700-22a6-11eb-895e-65651575fff9.png)

If we call the reloading pulling the screen down then we can see the correct loading skeleton showing up

![image](https://user-images.githubusercontent.com/8658164/98566183-60dddb80-22a6-11eb-908a-cdc0e35df41e.png)

Reported in WCiOS 5.4 beta testing.

**Comment by pmusolino** [comment] 2021-01-18 15:32
I investigated this issue. it seems that this is caused by the implementation of `ProductsTabProductTableViewCell`, which compact the labels inside the cell if there is no content. So, one solution, but not ideal, would be to use a fake table view cell with the appearance of `ProductsTabProductTableViewCell`. At the same time, if we update this cell, we should remember to update also the fake one.

**Comment by joshheald** [comment] 2022-05-24 10:03
I can no longer reproduce this, it was likely fixed in the PRs relating to #2448

**Closed as completed by joshheald** 2022-05-24 10:03 UTC
Labels: type: bug, feature: product list, priority: low
