### ISSUE TITLE
Stats module disabled

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-ios#932] opened 2019-04-29 21:16 UTC
If a user does not have the stats module enabled in their store, there should be a way in the app to disable checking for it so the user doesn't constantly get popup warnings. zen-1991018

**Comment by jkmassel** [comment] 2019-05-01 16:25
Possibly related – I keep getting this popup 
![Simulator Screen Shot - iPhone Xs - 2019-05-01 at 10 21 54](https://user-images.githubusercontent.com/1123407/57028067-4c257f80-6bfb-11e9-9d33-fdcf3f08816c.png)

From the logs:

```
Dashboard (Top Performers) — Error synchronizing top earner stats: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "name", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))
```

```
2019-05-01 10:20:01.147276-0600 WooCommerce[23583:18262729] ⛔️ Error loading dashboard: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "name", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))
```

Site ID 161477129 is currently consistently demonstrating the issue.

**Comment by mindgraffiti** [comment] 2019-05-07 17:51
Marking as high priority because this issue is trending in Zendesk, as well as being consistently reproduced internally.

**Comment by mindgraffiti** [comment] 2019-05-07 17:53
This is a 2-part bug:

1. Stats are not loading properly for correctly configured sites
2. Stats error message should be muted / not display any more if a user has disabled Stats in Jetpack.

**Comment by mindgraffiti** [comment] 2019-05-08 16:35
```2019/05/08 17:35:51:232  <> Mapping Error: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "name", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))
2019/05/08 17:35:51:232  ⛔️ Dashboard (Top Performers) — Error synchronizing top earner stats: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "name", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))
2019/05/08 17:35:51:237  <> Mapping Error: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "name", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))
2019/05/08 17:35:51:237  ⛔️ Dashboard (Top Performers) — Error synchronizing top earner stats: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "name", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))
2019/05/08 17:35:51:237  <> Mapping Error: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "name", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))
2019/05/08 17:35:51:237  ⛔️ Dashboard (Top Performers) — Error synchronizing top earner stats: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "name", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))
2019/05/08 17:35:51:238  <> Mapping Error: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "name", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))
2019/05/08 17:35:51:238  ⛔️ Dashboard (Top Performers) — Error synchronizing top earner stats: valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "name", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))```

From 2017209-zen

**Closed** 2019-07-16 18:10 UTC
Labels: Store Stats, [Type] Bug
