### ISSUE TITLE
Orders: Order badge count doesn't update after syncing remote changes to Processing orders

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#2109] opened 2020-04-08 13:59 UTC
**Describe the bug**

The app has an Order badge with the number of orders with Processing status. This badge correctly updates when changing an order's status from Processing to something else (e.g. when fulfilling an order) within the app.

However, after syncing remote changes to an order's status, the badge count doesn't update until the app is relaunched.

**To Reproduce**

1. Go to the Orders tab in the app.
2. Select the Processing tab and identify an order in the list.
3. In WP Admin, change the order’s status to something other than Processing.
4. In the app, pull to refresh the Processing list. Notice that the badge count on the Orders tab doesn't change. (You can also compare the count in the app to the count in WP Admin to confirm.)
5. Swipe to close the app.
6. Relaunch the app and notice that the badge count is now updated.

**Expected behavior**

I expect the badge count to update when the Processing orders list is synced.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.4
- WooCommerce iOS version: 4.0.0.0 TestFlight beta

**Comment by itsmeichigo** [comment] 2022-03-03 04:17
Closing since this issue is no longer reproducible - probably fixed in #4251 or some older PR.

**Closed by itsmeichigo** 2022-03-03 04:17 UTC
Labels: type: bug, feature: order list
