### ISSUE TITLE
[Mobile Payments] [SDK 2] After updating reader software, old version information is still displayed

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5325] opened 2021-11-02 17:50 UTC
Found during testing of #5322

After successfully updating a reader, the old version was still displayed:

![IMG_0224](https://user-images.githubusercontent.com/1595739/139918880-e0c21598-04e2-4e6d-819f-4b91a4f68e03.PNG)

After disconnecting and reconnecting the new version was properly displayed:

![IMG_0225](https://user-images.githubusercontent.com/1595739/139918893-b1b4f0b8-be5c-47ef-addf-c9a9a0609260.PNG)

**Comment by joshheald** [comment] 2021-12-02 17:56
I can't reproduce this without a reader that needs an update, but there's a reasonable chance that it will have been fixed by 23d91df

Placing On Hold until we get a new update on a reader to test with.

**Comment by joshheald** [comment] 2021-12-02 18:20
Did some further checks and `updateProperties()` was not called for simulated updates when they completed, as the `connectedReaders` array isn't updated. I'm going to add a speculative fix on `StripeCardReaderService` to send the reader again after the `softwareUpdateSubject.send(.completed)` event.

**Comment by joshheald** [comment] 2021-12-02 18:27
Turns out, simulated updates *do* report a new version number, if you grab the card reader from the event!

**Closed as completed** 2021-12-03 07:09 UTC
Labels: type: bug, feature: mobile payments
