### ISSUE TITLE
[Mobile Payments] Uncertainty around available actions on post-payment receipt modal

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#4584] opened 2021-07-09 10:50 UTC
**Describe the issue**

When I saw the receipt modal after taking a payment in the app, I had some decision panic. I wasn’t sure if I’d have the option to print/email the receipt later, and I wondered if I’d be able to do both or it was an either/or thing.

It turned out that I could only print or email the receipt from that modal (not both - the modal closed after I selected an action there). I could print the receipt later from the Order Detail screen, but I didn't have the option to email the receipt later.

@woocommerce/mobile-designers Is there a way to clarify those options or otherwise reduce the uncertainty/panic around that decision?

**To Reproduce**
1. Make sure your store is set up to accept in-person payments.
2. Create a new order.
3. Open the order detail in the app.
4. Tap "Collect Payment" and follow the instructions to accept payment for the order.
5. Once the payment is collected, notice a modal appears with three options for the receipt (print, email, or no action).

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/125067031-9d6b0c80-e0ab-11eb-8ded-558312266869.PNG" width="300px">

**Comment by joshheald** [comment] 2021-10-14 15:30
Android's fix has been to replace the `No thanks` button (I think it says `Return to order` now) with `Save receipt & continue`.
We could do the same here, though we don't strictly _save_ the receipt, when you get back to the order it is still accessible. At least until you leave the order. That's going to be fixed too though.

**Comment by ctarda** [comment] 2021-10-14 16:44
> we don't strictly save the receipt, when you get back to the order it is still accessible. At least until you leave the order. That's going to be fixed too though.

If that's the current behaviour, it is a regression. The data to render receipts on the fly was supposed to be saved to a plist file when payment has been captured successfully

**Comment by joshheald** [comment] 2021-10-14 17:03
@ctarda Actually, I don't think that receipt saving is broken after all, I've just confused myself by taking payments for the same site on different devices... sorry for causing concern! I'll keep an eye on it tomorrow to make sure.

Obviously it would be nice to be able to get the receipt even if it was done on another device too...

**Comment by kidinov** [comment] 2022-05-16 08:11
It looks like it's been fixed already

<img width="416" alt="image" src="https://user-images.githubusercontent.com/4923871/168548307-6dd68d5d-a6c1-4204-964c-4fea40b9825c.png">

**Closed as completed by kidinov** 2022-05-16 08:11 UTC
Labels: needs: design, feature: mobile payments, category: design
