### ISSUE TITLE
WooCommerce Admin button links to WordPress.com My Home page

### ISSUE THREAD

**Issue by rezzap** [woocommerce/woocommerce-ios#9048] opened 2023-03-06 13:18 UTC
**Describe the bug**
The WooCommerce admin link from the Menu options used to link to your site's wp-admin dashboard, but it now links to the WordPress.com My Home page which isn't relevant for WooCommerce settings on a self-hosted site. 

**To Reproduce**
1. Go to Menu
2. Click on WooCommerce Admin
3. Notice the in app browser will open My Home page (it's linked to my primary WordPress.com site which is different than the site I have selected in the app) without an option to manage the site settings anywhere
4. Click the link to open the site in a new browser window, and you end up logged in to the site in a browser with WordPress.com. You need to hold down on the WordPress admin bar to be able to open in a new browser window the login flow, but it brings you to the admin of the WordPress.com site not the site set in the app. 

**Screenshots**
https://user-images.githubusercontent.com/10325627/223119738-1c9ac8a3-6a9f-4cab-be8f-316f1314ed3b.MP4

**Expected behavior**
I would expect to immediately be brought to my site's wp-admin or dashboard or required to log in to the site. 

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 14
- iOS version: 16.2
- WooCommerce iOS version: 12.4.1 (12.4.1.0)

Replicated on multiple type of sites, one in the screenshot is self-hosted. 
User report: 6016540-zd-woothemes

**Comment by reginabally** [comment] 2023-03-06 14:26
Hi @itsmeichigo, do you think this is related to the change in #8822? I was able to reproduce this consistently on 12.4.1 on my iPhone, but not on the Xcode Simulator with the latest build.

**Comment by itsmeichigo** [comment] 2023-03-06 15:03
Yes, that PR should be the cause. @Ecarrion found that the issue happens only when logging in to self-hosted sites with WPCom credentials. I'll add a fix for this soon.

**Comment by Ecarrion** [comment] 2023-03-07 13:09
closing as https://github.com/woocommerce/woocommerce-ios/pull/9049 is merged

**Closed as completed by Ecarrion** 2023-03-07 13:09 UTC
Labels: type: bug, feature: hub menu
