### ISSUE TITLE
Orders: Badge count on app icon doesn't update after editing order status

### ISSUE THREAD

**Issue by thabotswana** [woocommerce/woocommerce-ios#5703] opened 2021-12-20 10:26 UTC
**Describe the bug**
Reported in 4624996-zen

The app icon has a badge with the number of orders with Processing status. This badge count doesn't update when changing an order's status (e.g. when fulfilling an order) within the app.

**To Reproduce**
1. Go to the Orders tab in the app.
2. Identify an order that needs processing.
3. Change the order’s status to something other than Processing.
4. Pull to refresh the Processing list. Notice that the badge count on the app icon doesn't change. 

https://user-images.githubusercontent.com/35628116/146751474-bf66d443-8820-4204-a5f0-d5729525b1e2.mp4

**Expected behavior**
I expect the badge count to update when the order status is changed.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
I was able to reproduce this in SSP with:
- Device: iPhone SE
- iOS version: 15.2
- WooCommerce iOS version: 8.1

**Comment by iamgabrielma** [comment] 2021-12-20 15:09
Another case reported on 5703-zen, the notification doesn't seem to disappear despite all orders marked as complete. 

> Version  8.1 (8.1.0.2)

|<img width="214" alt="Screenshot 2021-12-20 at 16 07 39" src="https://user-images.githubusercontent.com/3812076/146788655-505d4e7b-9e32-4239-a785-d6249a3b8eb4.png">|<img width="216" alt="Screenshot 2021-12-20 at 16 08 03" src="https://user-images.githubusercontent.com/3812076/146788722-ce099068-4ad6-4c80-a457-b1c0bc82f5e3.png">|

**Comment by mdrockwell** [comment] 2021-12-20 15:17
Another report here: 4626407-zd-woothemes

**Comment by jerrysarcastic** [comment] 2021-12-21 18:06
Also reported to us via social media:

https://twitter.com/twittlik/status/1473288196150771717

Screenshot:

<img width="601" alt="Screenshot on 2021-12-21 at 10-04-45" src="https://user-images.githubusercontent.com/1967448/146977603-8675747d-f8d7-458d-b2ae-bead95f8e568.png">

<img width="599" alt="Screenshot on 2021-12-21 at 10-06-03" src="https://user-images.githubusercontent.com/1967448/146977691-292c9e93-e841-4209-a0f5-0afde23ec517.png">

**Comment by jaclync** [comment] 2021-12-22 02:11
Shall we merge this issue with #1388? A hotfix release 8.1.1 is scheduled to fix this issue (p1640101931099100-slack-C5ALGJYEP)!

**Comment by joashrajin** [comment] 2022-09-09 07:18
+1 at #5524169-zen

The user has shared screenshots showing that they have no notifications within the app and have viewed all orders, but the badge continues to show one notification. The only fix they have found was to sign out and then back into the app

**Comment by ezebecke** [comment] 2022-09-09 20:58
+1 at #[5537399-zen](5537399-zd-woothemes)

**Comment by igotdes** [comment] 2022-09-12 03:21
Also reported in #5545789-zen:

> A 1 remains on the app icon (badge)

**Comment by ezebecke** [comment] 2022-09-14 19:00
+1 #[5541414-zen](5541414-zd-woothemes)

**Comment by jaclync** [comment] 2022-09-15 05:05
Took a look at the previous fix https://github.com/woocommerce/woocommerce-ios/pull/5715, and it seems like the call to reset the app badge count was removed in another PR a month ago https://github.com/woocommerce/woocommerce-ios/pull/7459. Asking the team in p1663204209893999-slack-C6H8C3G23

**Comment by erricgunawan** [comment] 2022-09-19 06:23
Two reviews from iOS App Store:

> In current version and with ios-16 the counter of unread messages is wrong again. In de huidige versie blijft het rode tellertje van nieuwe orders staan terwijl alles is gesynced. Verder mooie app!

4-star | Sep-15, 2022 | Version 10.2

--

Translated:

> The red one always stays days after the order has been processed or even deleted. Only at the top, when you open it, there is nothing to see to edit it. Aljes also super slow 😒

1-star | Sep-17, 2022 | Version 10.2

**Comment by ealeksandrov** [comment] 2022-09-19 07:52
The fix for app icon badge is implemented and scheduled for release in 10.4 on Sep 26.

**Comment by joashrajin** [comment] 2022-09-29 11:28
+1 at #5593756-zen

**Comment by shiki** [comment] 2022-09-30 01:13
@ealeksandrov Should this issue be closed?

**Comment by ealeksandrov** [comment] 2022-09-30 09:14
@shiki yes, lets check where latest report is coming from and then close the issue.
@joashrajin can you check what is app version for 5593756-zen? (I don't have the access)

**Comment by joashrajin** [comment] 2022-09-30 09:33
@ealeksandrov they did not contact us via the app, so we don't have the logs to check :( 

I am assuming they probably aren't using 10.4 as yet. I will add an update if they get back to us

**Comment by ealeksandrov** [comment] 2022-09-30 10:35
@joashrajin thanks for checking!
I'll close the issue for now, since solution is released and we don't have confirmed reports from newer versions.

**Comment by jostnes** [comment] 2022-10-19 09:59
There's a new report in 5635584-zd-woothemes - the merchant is using v10.6.0.2. Should we re-open this or create a new one for tracking?

**Comment by ealeksandrov** [comment] 2022-10-20 18:06
I've tested the app on [v10.6](https://github.com/woocommerce/woocommerce-ios/releases/tag/10.6). App badge handling related to orders works well.

Application badge is also displayed if there are any unread product reviews - it may be the case for this report.
In this example notice small badge on menu tab button (bottom right):
<img width=350 src="https://user-images.githubusercontent.com/3132438/197023344-9a085882-5b8a-48cc-ac23-0c4db593cb05.jpeg">
To clear it go to `Menu` > `Reviews` (unfortunately we don't highlight reviews button, it could be improved).

So the "1" app icon badge is displayed when there are new orders AND/OR new reviews. To clear it:
- open orders list (tab "Orders")
- open reviews list (tab "Menu" > button "Reviews")

**Comment by jostnes** [comment] 2022-10-21 02:42
Thanks @ealeksandrov for the quick reply and suggestion. I've responded to the merchant to check their reviews to confirm that the notification badge is from reviews.

**Comment by ealeksandrov** [comment] 2022-10-31 08:32
Closing this for now as we can't reproduce the issue and didn't hear back from the merchant.

**Closed as completed by ealeksandrov** 2022-10-31 08:32 UTC
