### ISSUE TITLE
Reviews: Marking as unapproved does not update the label

### ISSUE THREAD

**Issue by kyleaparker** [woocommerce/woocommerce-ios#612] opened 2019-01-15 01:17 UTC
**Describe the bug**
Unchecking the Approved button on a Review doesn't do anything. The notification shows that the review has been marked unapproved but if you click back through into the review, it is still showing as approved. 

I checked in wp-admin and the review has been marked as unapproved, it's just visually showing as approved in the app. 

**To Reproduce**
Steps to reproduce the behaviour:
1. In Notifications, click on a review
2. Click on "approved"
3. Click back into the review
4. Notice that it's still marked as Approved

**Screenshots**
![img_0417](https://user-images.githubusercontent.com/712873/51151512-1371cc80-18d0-11e9-9eef-803bde869cee.PNG)

**Expected behavior**
The correct state should be reflected on the review

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: 
- iOS version: 
- WooCommerce iOS version: 

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by ctarda** [comment] 2019-07-17 11:53
This is undergoing investigation by the friendly backend folks as mentioned in p99K0U-1mi-p2 (comment 3175)

**Comment by ctarda** [comment] 2019-07-18 11:16
There is a PR to solve the issue on the backend side:
https://github.com/Automattic/jetpack/pull/13079

**Comment by ctarda** [comment] 2019-07-22 20:00
Closing as there is a Jetpack release scheduled with a fix:

https://github.com/Automattic/jetpack/pull/13079#issuecomment-512536338

**Comment by rachelmcr** [comment] 2019-09-03 17:10
I am still seeing this issue on a site using the latest Jetpack release (7.7) and Woo iOS 2.6 (TestFlight beta), using the same steps as in the original report.

Approving/unapproving a review does not update when I open the review detail, or when I pull to refresh the list of reviews. It only updates when I pull to refresh the review detail.

**Comment by pmusolino** [comment] 2019-12-12 11:11
I'm closing this issue since in the release 3.2 I'm no more able to reproduce the issue.

**Closed by pmusolino** 2019-12-12 11:11 UTC
Labels: Notifications, [Type] Bug
