### ISSUE TITLE
Crashing at opening for many users

### ISSUE THREAD

**Issue by msilbers** [woocommerce/woocommerce-ios#2090] opened 2020-04-05 16:34 UTC
WooCommerce 3.8, iOS

**Describe the bug**
We have a few app reviews indicating that WooCommerce iOS is crashing when opening. We are awaiting responses with more details but since it was several, I wanted to report it right away.

> "Since the latest update, the app just closes as soon as I open it. I get notifications, but that is about it..."

> "For now a 1 star, when you “Oke” the admin plug-in the app crashes and can’t be openend anymore. After a reinstall the same problems. Wordpress site is running al the latest updates."

> Translated: "I would really like to use this App, but I can't do it. As soon as I open the application, it closes after a few seconds. However, I had time to configure and everything worked, but after selecting "test the experimental phase for product modification", the App closed abruptly and from that moment it was no longer possible to use it. Is there any way to fix it?"

> "It looked very promising at first but the app doesn’t work on my phone although it should. As soon as I open the app it starts loading, then it crushes down, meaning it’s being closed. So I can’t use the app. Please fix it, because I need it."

> Translated: "After the last update the app DOES NOT OPEN"

> Constant crashes as of today... starts to load and then shuts itself down. Multiple users in our business have had this issue.

> Translated: "Works great when it works ... but pops out very often"

**Comment by jaclync** [comment] 2020-04-06 01:25
hey @msilbers thanks a lot for reporting, this is very helpful! I just checked the date and App Store country for the reviews you mentioned, and it's consistent with @astralbodies's theory where daily saving time change is the root cause since we've seen spikes on Mar 8/9, Mar 29, and Apr 5, which are the dates where many countries begin or end daily saving time. So far we have https://github.com/woocommerce/woocommerce-ios/pull/2063 that logged the error instead of crashing the app when the same issue occurs (cannot parse the stats interval dates), and in the meantime I'm going to try reproducing the issue by changing my store to a country with DST and the date to the day of DST change.

review | date | App Store region
-- | -- | --
"Since the latest update, the app just closes as soon as I open it. I get notifications, but that is about it..." | Mar 29, 2020 | Sweden
"For now a 1 star, when you “Oke” the admin plug-in the app crashes and can’t be openend anymore. After a reinstall the same problems. Wordpress site is running al the latest updates." | Mar 29, 2020 | Netherlands
"It looked very promising at first but the app doesn’t work on my phone although it should. As soon as I open the app it starts loading, then it crushes down, meaning it’s being closed. So I can’t use the app. Please fix it, because I need it." | Mar 30, 2020 | Germany
Constant crashes as of today... starts to load and then shuts itself down. Multiple users in our business have had this issue. | Mar 30, 2020 | UK
"Vorrei davvero usare quest’App, ma non riesco a farlo. Appena apro l’applicazione, si chiude dopo pochi secondi. Avevo avuto però il tempo di configurare è tutto funzionava, ma dopo aver selezionato “testa la fase sperimentale per la modifica dei prodotti”, l’App si è chiusa bruscamente è da quel momento non è stato più possibile usarla. C’è modo di rimediare? Grazie" Translated: "I would really like to use this App, but I can't do it. As soon as I open the application, it closes after a few seconds. However, I had time to configure and everything worked, but after selecting "test the experimental phase for product modification", the App closed abruptly and from that moment it was no longer possible to use it. Is there any way to fix it?" | Mar 29, 2020 | Italy
"Dopo l’ultimo aggiornamento l’app NON SI APRE" Translated: "After the last update the app DOES NOT OPEN" | Mar 30, 2020 | Italy
"Werkt prima als hij werkt... maar klapt er wel heel vaak uit" Translated: "Works great when it works ... but pops out very often" | Mar 31, 2020 | Netherlands

**Comment by leandroprz** [comment] 2020-04-06 16:40
I'm experiencing this as well on my 6s running iOS 13.3 after the last update. I downloaded the app from the US AppStore but I'm located in Argentina.

**Comment by shiki** [comment] 2020-07-27 19:48
This may be related to #2371.

**Comment by shiki** [comment] 2020-08-24 22:55
@msilbers Do you still notice a trend in startup crashes? 

Since version 4.6 which included a fix for a crash (#2481), we've noticed a significant decrease in the number of crashes. Ref p91TBi-37L-p2. I'm curious whether that fixed the issue being discussed here.

**Comment by shiki** [comment] 2020-09-18 22:26
I'm going to close this now. We have significantly decreased the number of crashes throughout the past few months. We do have a few startup crashes left that we're not sure what the reasons are yet. We'll be tracking them #2667.

**Closed by shiki** 2020-09-18 22:26 UTC
Labels: [Type] Crash
