### ISSUE TITLE
Payment fails on orders with 0,00 total amount

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-ios#4559] opened 2021-07-06 13:10 UTC
**Describe the bug**
Card-Present Payments seems to not work when order has no products.

**To Reproduce**
1. Have a test site eligible to test CPP
1. Create an order without products so total amount will be 0,00
1. Go to order details
2. Click on `Collect Payment`
3. See "Payment failed" dialog

**Screenshots**

https://user-images.githubusercontent.com/5845095/124605087-dc128400-de6b-11eb-8941-9d0231a788db.mp4

**Expected behavior**

I'm not sure what's the expected behaviour but Android doesn't show `Collect Payment` at all for the same order - maybe it's something we want to go with too on iOS:

<img width="300" alt="Screenshot 2021-07-06 at 14 47 02" src="https://user-images.githubusercontent.com/5845095/124605275-082e0500-de6c-11eb-879c-e2f6c5e65b28.png">

**Mobile Environment**
Please include:
- Device: iPhone X
- iOS version: 14.6
- WooCommerce iOS version: 7.0.0

**Comment by allendav** [comment] 2021-07-06 15:11
It is likely this is because I don't think you can create a zero amount payment intent.

**Comment by wzieba** [comment] 2021-07-07 09:17
Yeah - that's totally a corner case. Do you think it's worth hiding the `Collect Payment` button for orders with 0,00 total amount or it's not worth it and we should close this issue?

**Comment by koke** [comment] 2021-07-07 09:57
Duplicate of #4254, we merged a fix in #4554 yesterday.

**Closed as completed by koke** 2021-07-07 09:57 UTC
Labels: type: bug, feature: mobile payments
