### ISSUE TITLE
[Orders List] Extra padding for some order items on  the order list

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-ios#13986] opened 2024-09-17 04:55 UTC
**Describe the bug**
In orders tab, sometimes, one of the item in the list seems to have an extra padding which looks weird. Pull-to-refresh solves this.

**To Reproduce**
1. Go to Orders tab
2. Pull-to-refresh multiple times
3. See that some of the items in the list will have extra start padding

![IMG_0009](https://github.com/user-attachments/assets/f7e4b219-f13e-4b94-a10f-9828f728bf72)
![IMG_0010](https://github.com/user-attachments/assets/b7f8a938-ff02-4ca9-8e75-efae3fc17cf4)

**Comment by dangermattic** [comment] 2024-09-17 04:55
Thanks for reporting! 👍

**Comment by rachelmcr** [comment] 2024-09-18 15:19
Thanks! Closing as a duplicate of https://github.com/woocommerce/woocommerce-ios/issues/12151.

**Closed as completed by rachelmcr** 2024-09-18 15:19 UTC
Labels: type: bug, feature: mobile payments
