### ISSUE TITLE
Reviews: product names and images are showing up as "Unknown" on the Product Review screen

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#4573] opened 2021-07-07 21:20 UTC
Steps to reproduce:

1. Go to Reviews.
1. Open any review detail.
1. Check to see if the product name appears correctly in the heading or not.

**Result:** the product name in the review details header says "Unknown" with a generic image for all products in review details. Comparatively, I can see the product name and image showing up correctly for the same reviews in the Android app.

iOS|Android|iOS|Android
---|---|---|---
<img src="https://user-images.githubusercontent.com/1119271/124828810-fcf2dc00-df34-11eb-80b4-17e5bd22a656.PNG" height="320" alt="IMG_4253">|<img src="https://user-images.githubusercontent.com/1119271/124828852-0c722500-df35-11eb-8a1d-5f129f1f184c.png" height="320" alt="Screenshot_20210707-145320">|<img src="https://user-images.githubusercontent.com/1119271/124828865-1136d900-df35-11eb-8806-7608f0cd2c13.PNG" height="320" alt="IMG_4255">|<img src="https://user-images.githubusercontent.com/1119271/124828870-14ca6000-df35-11eb-9396-7f62534be7bd.png" height="320" alt="Screenshot_20210707-145722">

<sup>Tested with WCiOS 7.0.0.1 TestFlight beta on iPhone 6S iOS 14.6 logged in as testuser01121 with worthwhile-seahorse.jurassic.ninja selected and running WP 5.7.2 JP 9.8.1 WC 5.5.0-rc.2.</sup>

Notes: I tested with WCiOS 6.9 (App Store version) and 6.8 (previous build from TestFlight) and saw the same problem in those versions. I also tested another site, testingallthetime.com, and saw the same problem on more than one site.

**Comment by rachelmcr** [comment] 2021-07-08 10:06
Thanks for the report! I'm going to close this as a duplicate of https://github.com/woocommerce/woocommerce-ios/issues/1907.

**Closed as completed by rachelmcr** 2021-07-08 10:06 UTC
Labels: type: bug, category: duplicate, feature: review details

**Comment by designsimply** [comment] 2021-07-08 19:33
Thanks Rachel!
