### ISSUE TITLE
Impossible to create a new store if the previous trial expired

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#10817] opened 2023-09-29 13:53 UTC
I tried to create a new store, from an account I used before to create a store. After the previous trial expired, it's almost impossible to create a new store.

How to replicate the issue:
1. Use an account with a trial expired.
2. Go to Menu -> Account
3. Press "Add a Store", then "Create a new store"
4. Follow the steps for creating a store.
5. The store creation process will be stuck on this screen for a while:
<img src="https://github.com/woocommerce/woocommerce-ios/assets/495617/befc190d-fdcc-4dc8-800f-11503d9deefc" width=300 />

6. After a while, I'll be redirected to this screen
<img src="https://github.com/woocommerce/woocommerce-ios/assets/495617/8aadff63-156b-412b-be78-a2900010763e" width=300 />

8. If I press "Retry" it will be stuck loading.
9. Going back to the store picker, I've no stores.

**Comment by JorgeMucientes** [comment] 2023-10-02 06:52
The issue was caused by a backend bug that has been fixed already. Closing this ticket.

**Closed as completed by JorgeMucientes** 2023-10-02 06:52 UTC
Labels: type: bug, priority: high, Store Creation
